/* SPDX-License-Identifier: Apache-2.0 */
/* SPDX-FileCopyrightText: 2026 Kaden Schutt <kaden@hipfire.dev> */

#ifndef REDLINE_DISPATCH_H
#define REDLINE_DISPATCH_H

/* Generated by cbindgen from redline-capi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define RL_OK 0

#define RL_ERR_NULL -1

#define RL_ERR_UTF8 -2

#define RL_ERR_RECORD -3

#define RL_ERR_COMPILE -4

#define RL_ERR_REPLAY -5

#define RL_ERR_HANDLE -6

#define RL_ERR_CERTIFICATION -7

/**
 * Replay tuning mode. `lanes`/`max_in_flight` are read from the call site.
 */
typedef enum RlMode {
    /**
     * One serial lane, terminal-signal completion (safest; == one stream).
     */
    Latency = 0,
    /**
     * `lanes` independent lanes overlap.
     */
    Overlap = 1,
    /**
     * Whole-graph overlap bounded by `max_in_flight`.
     */
    Throughput = 2,
} RlMode;

/**
 * Scheduler profile recorded by a verified Radiowave manifest.
 */
typedef enum RlSchedulerProfile {
    RlSchedulerUnknown = 0,
    RlSchedulerDefault = 1,
    RlSchedulerMaxIlp = 2,
    RlSchedulerIterativeIlp = 3,
    RlSchedulerMemoryClause = 4,
    RlSchedulerPipelineIlp = 5,
} RlSchedulerProfile;

/**
 * Mutable-resource read-cache classification from a verified Radiowave
 * manifest. Missing modules/kernels return `RlMutableScalarOrUnknown` and therefore
 * retain the fail-closed scalar-cache invalidation.
 */
typedef enum RlMutableReadCache {
    RlMutableScalarOrUnknown = 0,
    RlMutableVmemOnly = 1,
} RlMutableReadCache;

/**
 * A GPU binding: ROCr runtime + selected device + kernarg pool.
 */
typedef struct RlGpu RlGpu;

/**
 * Opaque capturing graph. Create with [`rl_graph_new`] / [`rl_graph_new_tuned`].
 */
typedef struct RlGraph RlGraph;

/**
 * Opaque instantiated graph (the analogue of `hipGraphExec_t`).
 */
typedef struct RlGraphExec RlGraphExec;

/**
 * A loaded code object; kernels are looked up from it by symbol.
 */
typedef struct RlModule RlModule;

/**
 * A builder accumulating dispatches into one PM4 command buffer.
 */
typedef struct RlPm4Builder RlPm4Builder;

/**
 * A finalized, retained PM4 indirect buffer, replayable end to end.
 */
typedef struct RlPm4Ib RlPm4Ib;

/**
 * One buffer access declared by a kernel node.
 */
typedef struct RlAccess {
    /**
     * Buffer handle returned by [`rl_graph_buffer`].
     */
    uint32_t buffer;
    uint64_t offset;
    uint64_t len;
    /**
     * `0` = read, non-zero = write.
     */
    uint8_t write;
} RlAccess;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create an empty graph with default (latency) tuning. Free with
 * [`rl_graph_free`].
 */
struct RlGraph *rl_graph_new(void);

/**
 * Create an empty graph with explicit tuning.
 */
struct RlGraph *rl_graph_new_tuned(uintptr_t lanes, enum RlMode mode, uintptr_t max_in_flight);

/**
 * Free a graph created by [`rl_graph_new`] / [`rl_graph_new_tuned`].
 *
 * # Safety
 * `g` must be a pointer returned by this library, or null.
 */
void rl_graph_free(struct RlGraph *g);

/**
 * Declare a device buffer (label + byte size). Writes an opaque buffer handle
 * to `out_handle`.
 *
 * # Safety
 * `g`, `label`, `out_handle` must be valid or null; `label` NUL-terminated.
 */
int32_t rl_graph_buffer(struct RlGraph *g, const char *label, uint64_t size, uint32_t *out_handle);

/**
 * Add a kernel node. `deps` are node handles (may be null/empty for a root);
 * `accesses` declares the buffer reads/writes. Writes the new node handle to
 * `out_handle`.
 *
 * # Safety
 * Pointers must be valid for their stated lengths or null; `name`
 * NUL-terminated.
 */
int32_t rl_graph_kernel(struct RlGraph *g,
                        const char *name,
                        uint32_t grid_x,
                        uint32_t grid_y,
                        uint32_t grid_z,
                        uint32_t block_x,
                        uint32_t block_y,
                        uint32_t block_z,
                        const struct RlAccess *accesses,
                        uintptr_t n_access,
                        const uint32_t *deps,
                        uintptr_t n_deps,
                        uint32_t *out_handle);

/**
 * Instantiate the captured graph into a replayable exec. Writes the exec
 * pointer to `out_exec`. Hazards are validated here; an unsafe graph returns
 * `RL_ERR_COMPILE`.
 *
 * # Safety
 * `g`, `out_exec` must be valid or null.
 */
int32_t rl_graph_instantiate(struct RlGraph *g, struct RlGraphExec **out_exec);

/**
 * Free an exec from [`rl_graph_instantiate`].
 *
 * # Safety
 * `e` must be a pointer returned by this library, or null.
 */
void rl_graphexec_free(struct RlGraphExec *e);

/**
 * Number of logical replay lanes the plan compiled to (0 if `e` is null).
 *
 * # Safety
 * `e` must be valid or null.
 */
uintptr_t rl_graphexec_lane_count(const struct RlGraphExec *e);

/**
 * Write the plan's 32-byte fingerprint to `out32`.
 *
 * # Safety
 * `e` valid or null; `out32` must point to at least 32 writable bytes.
 */
int32_t rl_graphexec_fingerprint(const struct RlGraphExec *e, uint8_t *out32);

/**
 * Validate the plan by replaying it once against the in-process mock backend
 * (no GPU). Confirms ordering and fences are consistent; returns `RL_OK` or
 * `RL_ERR_REPLAY`. Real HIP / public-AQL replay is bound at integration time.
 *
 * # Safety
 * `e` must be valid or null.
 */
int32_t rl_graphexec_launch_mock(const struct RlGraphExec *e);

/**
 * ABI version of this library.
 */
uint32_t rl_abi_version(void);

/**
 * Bind ROCr GPU `device_ordinal` (of the `ROCR_VISIBLE_DEVICES` set). Returns
 * null on failure. Free with [`rl_gpu_free`].
 */
struct RlGpu *rl_gpu_new(int32_t device_ordinal);

/**
 * # Safety
 * `gpu` must be a pointer from [`rl_gpu_new`], or null.
 */
void rl_gpu_free(struct RlGpu *gpu);

/**
 * Load a code object (HSACO bytes). Writes the module pointer to `out`.
 *
 * # Safety
 * `gpu`/`out` valid or null; `code` valid for `len` bytes.
 */
int32_t rl_gpu_load_module(const struct RlGpu *gpu,
                           const uint8_t *code,
                           uintptr_t len,
                           struct RlModule **out);

/**
 * Load a code object only after verifying its Radiowave JSON manifest binds
 * to these exact bytes and contains code-object inspection evidence.
 *
 * # Safety
 * `gpu`/`out` valid or null; `code` and `manifest` valid for their stated
 * lengths. The manifest need not be NUL-terminated.
 */
int32_t rl_gpu_load_module_radiowave(const struct RlGpu *gpu,
                                     const uint8_t *code,
                                     uintptr_t len,
                                     const uint8_t *manifest,
                                     uintptr_t manifest_len,
                                     struct RlModule **out);

/**
 * # Safety
 * `module` from [`rl_gpu_load_module`], or null.
 */
void rl_module_free(struct RlModule *module);

/**
 * The kernarg segment size (bytes) the engine must supply for `symbol`, or -1.
 *
 * # Safety
 * `module`/`symbol` valid or null; `symbol` NUL-terminated.
 */
int64_t rl_module_kernarg_size(const struct RlModule *module, const char *symbol);

/**
 * Whether `module` was loaded with and verified against a Radiowave manifest.
 *
 * # Safety
 * `module` from a module-load function, or null.
 */
bool rl_module_radiowave_certified(const struct RlModule *module);

/**
 * Scheduler profile in the verified manifest, or `RlSchedulerUnknown`.
 *
 * # Safety
 * `module` from a module-load function, or null.
 */
enum RlSchedulerProfile rl_module_scheduler_profile(const struct RlModule *module);

/**
 * Wavefront width in the verified manifest, or zero for an uncertified/null
 * module.
 *
 * # Safety
 * `module` from a module-load function, or null.
 */
uint32_t rl_module_wavefront_size(const struct RlModule *module);

/**
 * Return the verified mutable-resource cache class for `symbol`. Unknown raw
 * modules, missing symbols, invalid UTF-8, and null pointers fail closed.
 *
 * # Safety
 * `module`/`symbol` valid or null; `symbol` NUL-terminated.
 */
enum RlMutableReadCache rl_module_kernel_read_cache(const struct RlModule *module,
                                                    const char *symbol);

/**
 * New PM4 builder bound to `gpu`. Free with [`rl_pm4_builder_free`] (or hand it
 * to [`rl_pm4_finalize`], which consumes it). Returns null on failure.
 *
 * # Safety
 * `gpu` valid or null.
 */
struct RlPm4Builder *rl_pm4_builder_new(const struct RlGpu *gpu);

/**
 * Record one dispatch: `symbol` from `module`, `grid`/`block` in **workitems**
 * (grid = gridDim × blockDim), `dynamic_group_bytes`, and `kernarg`/`kernarg_len`
 * = the engine's kernarg segment (zero-padded / truncated to the kernel's size).
 *
 * # Safety
 * Pointers valid or null; `symbol` NUL-terminated; `kernarg` valid for
 * `kernarg_len`.
 */
int32_t rl_pm4_dispatch(struct RlPm4Builder *builder,
                        const struct RlModule *module,
                        const char *symbol,
                        uint32_t grid_x,
                        uint32_t grid_y,
                        uint32_t grid_z,
                        uint32_t block_x,
                        uint32_t block_y,
                        uint32_t block_z,
                        uint32_t dynamic_group_bytes,
                        const uint8_t *kernarg,
                        uintptr_t kernarg_len);

/**
 * Insert a dependency boundary after the dispatches recorded so far: wait for
 * the writer to retire, then invalidate scalar/vector read caches so the next
 * dispatch sees its L2-committed output. Required for a non-atomic read-modify-
 * write chain (decode); still the minimal gfx12 fence (L2/MALL stays coherent).
 *
 * # Safety
 * `builder` valid or null.
 */
void rl_pm4_wait_idle(struct RlPm4Builder *builder);

/**
 * Insert a same-agent RMW dependency selected for the next consumer. A
 * verified VMEM-only Radiowave consumer omits the unrelated scalar-cache
 * invalidation; every raw, missing, or ambiguous consumer uses the generic
 * fail-closed boundary.
 *
 * # Safety
 * `builder`/`module` valid or null; `consumer_symbol` NUL-terminated.
 */
int32_t rl_pm4_wait_rmw(struct RlPm4Builder *builder,
                        const struct RlModule *module,
                        const char *consumer_symbol);

/**
 * # Safety
 * `builder` from [`rl_pm4_builder_new`] and NOT already finalized, or null.
 */
void rl_pm4_builder_free(struct RlPm4Builder *builder);

/**
 * Lower the builder into a retained PM4 IB. **Consumes `builder`** (do not use
 * or free it after this). Writes the IB pointer to `out`.
 *
 * # Safety
 * `gpu`/`out` valid or null; `builder` a live, un-finalized builder pointer.
 */
int32_t rl_pm4_finalize(const struct RlGpu *gpu,
                        struct RlPm4Builder *builder,
                        struct RlPm4Ib **out);

/**
 * Profiled form of [`rl_pm4_finalize`]. The resulting IB can be replayed with
 * [`rl_pm4_replay_profiled`] to obtain the GPU execution span in microseconds.
 *
 * # Safety
 * Identical to [`rl_pm4_finalize`].
 */
int32_t rl_pm4_finalize_profiled(const struct RlGpu *gpu,
                                 struct RlPm4Builder *builder,
                                 struct RlPm4Ib **out);

/**
 * Replay the retained IB once (submit + wait for completion). Returns `RL_OK`.
 *
 * # Safety
 * `ib` from [`rl_pm4_finalize`], or null; every device pointer encoded in the
 * engine's kernargs must remain valid.
 */
int32_t rl_pm4_replay(struct RlPm4Ib *ib);

/**
 * Replay a profiled retained IB and write its GPU execution span in
 * microseconds to `out_gpu_us`.
 *
 * # Safety
 * `ib` must come from [`rl_pm4_finalize_profiled`]; `out_gpu_us` must be a
 * valid writable pointer. Pointee lifetimes match [`rl_pm4_replay`].
 */
int32_t rl_pm4_replay_profiled(struct RlPm4Ib *ib, double *out_gpu_us);

/**
 * # Safety
 * `ib` from [`rl_pm4_finalize`], or null.
 */
void rl_pm4_ib_free(struct RlPm4Ib *ib);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* REDLINE_DISPATCH_H */
