/* SPDX-License-Identifier: Apache-2.0 */
/* SPDX-FileCopyrightText: 2026 Kaden Schutt <kaden@hipfire.dev> */

#ifndef REDLINE_DISPATCH_H
#define REDLINE_DISPATCH_H

/* Generated by cbindgen from redline-capi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define RL_OK 0

#define RL_ERR_NULL -1

#define RL_ERR_UTF8 -2

#define RL_ERR_RECORD -3

#define RL_ERR_COMPILE -4

#define RL_ERR_REPLAY -5

#define RL_ERR_HANDLE -6

/**
 * Replay tuning mode. `lanes`/`max_in_flight` are read from the call site.
 */
typedef enum RlMode {
    /**
     * One serial lane, terminal-signal completion (safest; == one stream).
     */
    Latency = 0,
    /**
     * `lanes` independent lanes overlap.
     */
    Overlap = 1,
    /**
     * Whole-graph overlap bounded by `max_in_flight`.
     */
    Throughput = 2,
} RlMode;

/**
 * Opaque capturing graph. Create with [`rl_graph_new`] / [`rl_graph_new_tuned`].
 */
typedef struct RlGraph RlGraph;

/**
 * Opaque instantiated graph (the analogue of `hipGraphExec_t`).
 */
typedef struct RlGraphExec RlGraphExec;

/**
 * One buffer access declared by a kernel node.
 */
typedef struct RlAccess {
    /**
     * Buffer handle returned by [`rl_graph_buffer`].
     */
    uint32_t buffer;
    uint64_t offset;
    uint64_t len;
    /**
     * `0` = read, non-zero = write.
     */
    uint8_t write;
} RlAccess;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create an empty graph with default (latency) tuning. Free with
 * [`rl_graph_free`].
 */
struct RlGraph *rl_graph_new(void);

/**
 * Create an empty graph with explicit tuning.
 */
struct RlGraph *rl_graph_new_tuned(uintptr_t lanes, enum RlMode mode, uintptr_t max_in_flight);

/**
 * Free a graph created by [`rl_graph_new`] / [`rl_graph_new_tuned`].
 *
 * # Safety
 * `g` must be a pointer returned by this library, or null.
 */
void rl_graph_free(struct RlGraph *g);

/**
 * Declare a device buffer (label + byte size). Writes an opaque buffer handle
 * to `out_handle`.
 *
 * # Safety
 * `g`, `label`, `out_handle` must be valid or null; `label` NUL-terminated.
 */
int32_t rl_graph_buffer(struct RlGraph *g, const char *label, uint64_t size, uint32_t *out_handle);

/**
 * Add a kernel node. `deps` are node handles (may be null/empty for a root);
 * `accesses` declares the buffer reads/writes. Writes the new node handle to
 * `out_handle`.
 *
 * # Safety
 * Pointers must be valid for their stated lengths or null; `name`
 * NUL-terminated.
 */
int32_t rl_graph_kernel(struct RlGraph *g,
                        const char *name,
                        uint32_t grid_x,
                        uint32_t grid_y,
                        uint32_t grid_z,
                        uint32_t block_x,
                        uint32_t block_y,
                        uint32_t block_z,
                        const struct RlAccess *accesses,
                        uintptr_t n_access,
                        const uint32_t *deps,
                        uintptr_t n_deps,
                        uint32_t *out_handle);

/**
 * Instantiate the captured graph into a replayable exec. Writes the exec
 * pointer to `out_exec`. Hazards are validated here; an unsafe graph returns
 * `RL_ERR_COMPILE`.
 *
 * # Safety
 * `g`, `out_exec` must be valid or null.
 */
int32_t rl_graph_instantiate(struct RlGraph *g, struct RlGraphExec **out_exec);

/**
 * Free an exec from [`rl_graph_instantiate`].
 *
 * # Safety
 * `e` must be a pointer returned by this library, or null.
 */
void rl_graphexec_free(struct RlGraphExec *e);

/**
 * Number of logical replay lanes the plan compiled to (0 if `e` is null).
 *
 * # Safety
 * `e` must be valid or null.
 */
uintptr_t rl_graphexec_lane_count(const struct RlGraphExec *e);

/**
 * Write the plan's 32-byte fingerprint to `out32`.
 *
 * # Safety
 * `e` valid or null; `out32` must point to at least 32 writable bytes.
 */
int32_t rl_graphexec_fingerprint(const struct RlGraphExec *e, uint8_t *out32);

/**
 * Validate the plan by replaying it once against the in-process mock backend
 * (no GPU). Confirms ordering and fences are consistent; returns `RL_OK` or
 * `RL_ERR_REPLAY`. Real HIP / public-AQL replay is bound at integration time.
 *
 * # Safety
 * `e` must be valid or null.
 */
int32_t rl_graphexec_launch_mock(const struct RlGraphExec *e);

/**
 * ABI version of this library.
 */
uint32_t rl_abi_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* REDLINE_DISPATCH_H */
