// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Kaden Schutt <kaden@hipfire.dev>
// Auto-generated by kernels/microwave/wrap.py — do not edit
#pragma once

// dot_q4 gfx1201 w32 vgprs=37 sgprs=128 parsed_max_v=43 parsed_max_s=7 code_size=780 lds=0 scratch=0
#define MICROWAVE_DOT_Q4_GFX1201_W32_BODY R"MW(.Lmw_dot_q4_gfx1201_w32_BB0:
	v_mov_b32_e32 v1, 0
	s_clause 0x1
	global_load_b128 v[4:7], v1, s[2:3]
	global_load_b96 v[8:10], v1, s[2:3] offset:16
	s_mul_i32 s4, ttmp9, s4
	s_delay_alu instid0(SALU_CYCLE_1)
	v_add_nc_u32_e32 v0, s4, v0
	s_wait_loadcnt 0x1
	v_readfirstlane_b32 s1, v5
	v_readfirstlane_b32 s5, v7
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s6, v9
	v_readfirstlane_b32 s7, v10
	v_cmpx_gt_u32_e32 v10, v0
	s_mov_b32 s4, s1
	s_cbranch_execz .Lmw_dot_q4_gfx1201_w32_BB11
.Lmw_dot_q4_gfx1201_w32_BB1:
	v_mov_b32_e32 v1, 0
	s_mov_b32 s0, 0
.Lmw_dot_q4_gfx1201_w32_BB2:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:28
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s1, v2
	s_cmp_ge_u32 s0, s1
	s_cbranch_scc1 .Lmw_dot_q4_gfx1201_w32_BB6
.Lmw_dot_q4_gfx1201_w32_BB5:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:36
	s_mul_i32 s1, s0, s7
	s_wait_alu 0xfffe
	v_add_lshl_u32 v3, s1, v0, 4
	s_wait_loadcnt 0x0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_and_b32_e32 v2, v2, v3
	v_lshrrev_b32_e32 v10, 2, v2
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_ashrrev_i32_e32 v11, 31, v10
	v_add_nc_u32_e32 v5, 4, v2
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v12, vcc_lo, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v13, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v14, vcc_lo, v6, v10
	v_lshrrev_b32_e32 v10, 2, v5
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v15, vcc_lo, s5, v11, vcc_lo
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v20, vcc_lo, v4, v10
	v_add_nc_u32_e32 v7, 8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v21, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v22, vcc_lo, v6, v10
	v_lshrrev_b32_e32 v10, 2, v7
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v23, vcc_lo, s5, v11, vcc_lo
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v28, vcc_lo, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v29, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v30, vcc_lo, v6, v10
	v_add_nc_u32_e32 v2, 12, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v31, vcc_lo, s5, v11, vcc_lo
	v_lshrrev_b32_e32 v2, 2, v2
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 4, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v10, vcc_lo, v4, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v11, vcc_lo, s4, v3, vcc_lo
	v_add_co_u32 v36, vcc_lo, v6, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v37, vcc_lo, s5, v3, vcc_lo
	s_clause 0x7
	global_load_b128 v[16:19], v[12:13], off
	global_load_b128 v[12:15], v[14:15], off
	global_load_b128 v[24:27], v[20:21], off
	global_load_b128 v[20:23], v[22:23], off
	global_load_b128 v[32:35], v[28:29], off
	global_load_b128 v[28:31], v[30:31], off
	global_load_b128 v[40:43], v[10:11], off
	global_load_b128 v[36:39], v[36:37], off
	s_add_co_u32 s0, s0, 1
	s_wait_loadcnt 0x6
	v_dot4_i32_iu8 v12, v12, v16, v1 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v13, v13, v17, v12 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v14, v14, v18, v13 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v15, v15, v19, v14 neg_lo:[1,0,0]
	s_wait_loadcnt 0x4
	v_dot4_i32_iu8 v20, v20, v24, v15 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v21, v21, v25, v20 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v22, v22, v26, v21 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v23, v23, v27, v22 neg_lo:[1,0,0]
	s_wait_loadcnt 0x2
	v_dot4_i32_iu8 v28, v28, v32, v23 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v29, v29, v33, v28 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v30, v30, v34, v29 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v31, v31, v35, v30 neg_lo:[1,0,0]
	s_wait_loadcnt 0x0
	v_dot4_i32_iu8 v36, v36, v40, v31 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v37, v37, v41, v36 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v38, v38, v42, v37 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1)
	v_dot4_i32_iu8 v1, v39, v43, v38 neg_lo:[1,0,0]
	s_branch .Lmw_dot_q4_gfx1201_w32_BB2
.Lmw_dot_q4_gfx1201_w32_BB6:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:32
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v2, v2, v0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 2, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v4, vcc_lo, v8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v5, vcc_lo, s6, v3, vcc_lo
	global_load_b32 v3, v[4:5], off
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v3, v3, v1
	global_store_b32 v[4:5], v3, off
.Lmw_dot_q4_gfx1201_w32_BB11:
	s_nop 0
	s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
	s_endpgm)MW"

// dot_q4 gfx1201 w64 vgprs=37 sgprs=128 parsed_max_v=43 parsed_max_s=7 code_size=776 lds=0 scratch=0
#define MICROWAVE_DOT_Q4_GFX1201_W64_BODY R"MW(.Lmw_dot_q4_gfx1201_w64_BB0:
	v_mov_b32_e32 v1, 0
	s_clause 0x1
	global_load_b128 v[4:7], v1, s[2:3]
	global_load_b96 v[8:10], v1, s[2:3] offset:16
	s_mul_i32 s4, ttmp9, s4
	s_delay_alu instid0(SALU_CYCLE_1)
	v_add_nc_u32_e32 v0, s4, v0
	s_wait_loadcnt 0x1
	v_readfirstlane_b32 s1, v5
	v_readfirstlane_b32 s5, v7
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s6, v9
	v_readfirstlane_b32 s7, v10
	v_cmpx_gt_u32_e32 v10, v0
	s_mov_b32 s4, s1
	s_cbranch_execz .Lmw_dot_q4_gfx1201_w64_BB11
.Lmw_dot_q4_gfx1201_w64_BB1:
	s_mov_b32 s0, 0
	v_mov_b32_e32 v1, 0
.Lmw_dot_q4_gfx1201_w64_BB2:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:28
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s1, v2
	s_cmp_ge_u32 s0, s1
	s_cbranch_scc1 .Lmw_dot_q4_gfx1201_w64_BB6
.Lmw_dot_q4_gfx1201_w64_BB5:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:36
	s_mul_i32 s1, s0, s7
	s_wait_alu 0xfffe
	v_add_lshl_u32 v3, s1, v0, 4
	s_wait_loadcnt 0x0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_and_b32_e32 v2, v2, v3
	v_add_nc_u32_e32 v7, 8, v2
	v_lshrrev_b32_e32 v10, 2, v2
	v_add_nc_u32_e32 v5, 4, v2
	s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v11, 31, v10
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v12, vcc, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v13, vcc, s4, v11, vcc
	v_add_co_u32 v14, vcc, v6, v10
	v_lshrrev_b32_e32 v10, 2, v5
	v_add_nc_u32_e32 v2, 12, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v15, vcc, s5, v11, vcc
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_lshrrev_b32_e32 v2, 2, v2
	v_add_co_u32 v16, vcc, v4, v10
	v_ashrrev_i32_e32 v3, 31, v2
	s_delay_alu instid0(VALU_DEP_1)
	v_lshlrev_b64_e64 v[2:3], 4, v[2:3]
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v17, vcc, s4, v11, vcc
	v_add_co_u32 v18, vcc, v6, v10
	v_lshrrev_b32_e32 v10, 2, v7
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v19, vcc, s5, v11, vcc
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v20, vcc, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v21, vcc, s4, v11, vcc
	v_add_co_u32 v22, vcc, v6, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v23, vcc, s5, v11, vcc
	v_add_co_u32 v10, vcc, v4, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v11, vcc, s4, v3, vcc
	v_add_co_u32 v24, vcc, v6, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v25, vcc, s5, v3, vcc
	s_clause 0x7
	global_load_b128 v[28:31], v[12:13], off
	global_load_b128 v[12:15], v[14:15], off
	global_load_b128 v[32:35], v[16:17], off
	global_load_b128 v[16:19], v[18:19], off
	global_load_b128 v[36:39], v[20:21], off
	global_load_b128 v[20:23], v[22:23], off
	global_load_b128 v[40:43], v[10:11], off
	global_load_b128 v[24:27], v[24:25], off
	s_add_co_u32 s0, s0, 1
	s_wait_loadcnt 0x6
	v_dot4_i32_iu8 v12, v12, v28, v1 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v13, v13, v29, v12 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v14, v14, v30, v13 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v15, v15, v31, v14 neg_lo:[1,0,0]
	s_wait_loadcnt 0x4
	v_dot4_i32_iu8 v16, v16, v32, v15 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v17, v17, v33, v16 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v18, v18, v34, v17 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v19, v19, v35, v18 neg_lo:[1,0,0]
	s_wait_loadcnt 0x2
	v_dot4_i32_iu8 v20, v20, v36, v19 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v21, v21, v37, v20 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v22, v22, v38, v21 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v23, v23, v39, v22 neg_lo:[1,0,0]
	s_wait_loadcnt 0x0
	v_dot4_i32_iu8 v24, v24, v40, v23 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v25, v25, v41, v24 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v26, v26, v42, v25 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1)
	v_dot4_i32_iu8 v1, v27, v43, v26 neg_lo:[1,0,0]
	s_branch .Lmw_dot_q4_gfx1201_w64_BB2
.Lmw_dot_q4_gfx1201_w64_BB6:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:32
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v2, v2, v0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 2, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v4, vcc, v8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v5, vcc, s6, v3, vcc
	global_load_b32 v3, v[4:5], off
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v3, v3, v1
	global_store_b32 v[4:5], v3, off
.Lmw_dot_q4_gfx1201_w64_BB11:
	s_nop 0
	s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
	s_endpgm)MW"

// dot_q6 gfx1201 w32 vgprs=38 sgprs=128 parsed_max_v=43 parsed_max_s=8 code_size=1128 lds=0 scratch=0
#define MICROWAVE_DOT_Q6_GFX1201_W32_BODY R"MW(.Lmw_dot_q6_gfx1201_w32_BB0:
	v_mov_b32_e32 v1, 0
	s_clause 0x1
	global_load_b128 v[4:7], v1, s[2:3]
	global_load_b96 v[8:10], v1, s[2:3] offset:16
	s_mul_i32 s4, ttmp9, s4
	s_delay_alu instid0(SALU_CYCLE_1)
	v_add_nc_u32_e32 v0, s4, v0
	s_wait_loadcnt 0x1
	v_readfirstlane_b32 s1, v5
	v_readfirstlane_b32 s5, v7
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s6, v9
	v_readfirstlane_b32 s7, v10
	v_cmpx_gt_u32_e32 v10, v0
	s_mov_b32 s4, s1
	s_cbranch_execz .Lmw_dot_q6_gfx1201_w32_BB11
.Lmw_dot_q6_gfx1201_w32_BB1:
	v_mov_b32_e32 v1, 0
	s_mov_b32 s0, 0
.Lmw_dot_q6_gfx1201_w32_BB2:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:28
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s1, v2
	s_cmp_ge_u32 s0, s1
	s_cbranch_scc1 .Lmw_dot_q6_gfx1201_w32_BB6
.Lmw_dot_q6_gfx1201_w32_BB5:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:36
	s_mul_i32 s1, s0, s7
	s_wait_alu 0xfffe
	v_add_lshl_u32 v3, s1, v0, 4
	s_wait_loadcnt 0x0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_and_b32_e32 v2, v2, v3
	v_lshrrev_b32_e32 v10, 2, v2
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_ashrrev_i32_e32 v11, 31, v10
	v_add_nc_u32_e32 v5, 4, v2
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v12, vcc_lo, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v13, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v14, vcc_lo, v6, v10
	v_lshrrev_b32_e32 v10, 2, v5
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v15, vcc_lo, s5, v11, vcc_lo
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v20, vcc_lo, v4, v10
	v_add_nc_u32_e32 v7, 8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v21, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v22, vcc_lo, v6, v10
	v_lshrrev_b32_e32 v10, 2, v7
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v23, vcc_lo, s5, v11, vcc_lo
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v28, vcc_lo, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v29, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v30, vcc_lo, v6, v10
	v_add_nc_u32_e32 v2, 12, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v31, vcc_lo, s5, v11, vcc_lo
	v_lshrrev_b32_e32 v2, 2, v2
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 4, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v10, vcc_lo, v4, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v11, vcc_lo, s4, v3, vcc_lo
	v_add_co_u32 v36, vcc_lo, v6, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v37, vcc_lo, s5, v3, vcc_lo
	s_clause 0x7
	global_load_b128 v[16:19], v[12:13], off
	global_load_b128 v[12:15], v[14:15], off
	global_load_b128 v[24:27], v[20:21], off
	global_load_b128 v[20:23], v[22:23], off
	global_load_b128 v[32:35], v[28:29], off
	global_load_b128 v[28:31], v[30:31], off
	global_load_b128 v[40:43], v[10:11], off
	global_load_b128 v[36:39], v[36:37], off
	s_mov_b32 s8, 0x1010101
	s_add_co_u32 s0, s0, 1
	s_wait_loadcnt 0x6
	s_wait_alu 0xfffe
	v_dot4_i32_iu8 v9, v12, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v10, v13, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v11, v14, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
	v_lshlrev_b32_e32 v9, 5, v9
	v_lshlrev_b32_e32 v10, 5, v10
	v_lshlrev_b32_e32 v11, 5, v11
	v_sub_nc_u32_e32 v9, 0, v9
	v_sub_nc_u32_e32 v10, 0, v10
	v_sub_nc_u32_e32 v11, 0, v11
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_2)
	v_dot4_i32_iu8 v12, v12, v16, v9 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v13, v13, v17, v10 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v14, v14, v18, v11 neg_lo:[1,0,0]
	v_add3_u32 v13, v13, v1, v12
	v_dot4_i32_iu8 v12, v15, s8, 0 neg_lo:[1,0,0]
	s_wait_loadcnt 0x4
	v_dot4_i32_iu8 v16, v23, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_4) | instid1(VALU_DEP_4)
	v_lshlrev_b32_e32 v12, 5, v12
	v_lshlrev_b32_e32 v16, 5, v16
	s_wait_loadcnt 0x2
	v_dot4_i32_iu8 v17, v28, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v18, v29, s8, 0 neg_lo:[1,0,0]
	v_sub_nc_u32_e32 v12, 0, v12
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
	v_lshlrev_b32_e32 v17, 5, v17
	v_lshlrev_b32_e32 v18, 5, v18
	v_dot4_i32_iu8 v15, v15, v19, v12 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v19, v30, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_4) | instid1(VALU_DEP_4)
	v_add3_u32 v15, v15, v13, v14
	v_dot4_i32_iu8 v13, v20, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v14, v21, s8, 0 neg_lo:[1,0,0]
	v_lshlrev_b32_e32 v19, 5, v19
	v_sub_nc_u32_e32 v16, 0, v16
	v_lshlrev_b32_e32 v13, 5, v13
	v_lshlrev_b32_e32 v14, 5, v14
	s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
	v_dot4_i32_iu8 v23, v23, v27, v16 neg_lo:[1,0,0]
	v_sub_nc_u32_e32 v13, 0, v13
	v_sub_nc_u32_e32 v14, 0, v14
	v_sub_nc_u32_e32 v17, 0, v17
	v_sub_nc_u32_e32 v18, 0, v18
	s_delay_alu instid0(VALU_DEP_4)
	v_dot4_i32_iu8 v20, v20, v24, v13 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v21, v21, v25, v14 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v28, v28, v32, v17 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v29, v29, v33, v18 neg_lo:[1,0,0]
	s_wait_loadcnt 0x0
	v_dot4_i32_iu8 v24, v39, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_4)
	v_add3_u32 v21, v21, v15, v20
	v_dot4_i32_iu8 v15, v22, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v20, v31, s8, 0 neg_lo:[1,0,0]
	v_sub_nc_u32_e32 v19, 0, v19
	v_lshlrev_b32_e32 v24, 5, v24
	v_lshlrev_b32_e32 v15, 5, v15
	v_lshlrev_b32_e32 v20, 5, v20
	v_dot4_i32_iu8 v30, v30, v34, v19 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_sub_nc_u32_e32 v15, 0, v15
	v_sub_nc_u32_e32 v20, 0, v20
	v_dot4_i32_iu8 v22, v22, v26, v15 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v31, v31, v35, v20 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_4)
	v_add3_u32 v23, v23, v21, v22
	v_dot4_i32_iu8 v21, v36, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v22, v37, s8, 0 neg_lo:[1,0,0]
	v_sub_nc_u32_e32 v24, 0, v24
	v_add3_u32 v29, v29, v23, v28
	v_dot4_i32_iu8 v23, v38, s8, 0 neg_lo:[1,0,0]
	v_lshlrev_b32_e32 v21, 5, v21
	v_lshlrev_b32_e32 v22, 5, v22
	v_dot4_i32_iu8 v39, v39, v43, v24 neg_lo:[1,0,0]
	v_add3_u32 v31, v31, v29, v30
	v_lshlrev_b32_e32 v23, 5, v23
	v_sub_nc_u32_e32 v21, 0, v21
	v_sub_nc_u32_e32 v22, 0, v22
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
	v_sub_nc_u32_e32 v23, 0, v23
	v_dot4_i32_iu8 v36, v36, v40, v21 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v37, v37, v41, v22 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v38, v38, v42, v23 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_add3_u32 v37, v37, v31, v36
	v_add3_u32 v1, v39, v37, v38
	s_branch .Lmw_dot_q6_gfx1201_w32_BB2
.Lmw_dot_q6_gfx1201_w32_BB6:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:32
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v2, v2, v0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 2, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v4, vcc_lo, v8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v5, vcc_lo, s6, v3, vcc_lo
	global_load_b32 v3, v[4:5], off
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v3, v3, v1
	global_store_b32 v[4:5], v3, off
.Lmw_dot_q6_gfx1201_w32_BB11:
	s_nop 0
	s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
	s_endpgm)MW"

// dot_q6 gfx1201 w64 vgprs=38 sgprs=128 parsed_max_v=43 parsed_max_s=8 code_size=1140 lds=0 scratch=0
#define MICROWAVE_DOT_Q6_GFX1201_W64_BODY R"MW(.Lmw_dot_q6_gfx1201_w64_BB0:
	v_mov_b32_e32 v1, 0
	s_clause 0x1
	global_load_b128 v[4:7], v1, s[2:3]
	global_load_b96 v[8:10], v1, s[2:3] offset:16
	s_mul_i32 s4, ttmp9, s4
	s_delay_alu instid0(SALU_CYCLE_1)
	v_add_nc_u32_e32 v0, s4, v0
	s_wait_loadcnt 0x1
	v_readfirstlane_b32 s1, v5
	v_readfirstlane_b32 s5, v7
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s6, v9
	v_readfirstlane_b32 s7, v10
	v_cmpx_gt_u32_e32 v10, v0
	s_mov_b32 s4, s1
	s_cbranch_execz .Lmw_dot_q6_gfx1201_w64_BB11
.Lmw_dot_q6_gfx1201_w64_BB1:
	s_mov_b32 s0, 0
	v_mov_b32_e32 v1, 0
.Lmw_dot_q6_gfx1201_w64_BB2:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:28
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s1, v2
	s_cmp_ge_u32 s0, s1
	s_cbranch_scc1 .Lmw_dot_q6_gfx1201_w64_BB6
.Lmw_dot_q6_gfx1201_w64_BB5:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:36
	s_mul_i32 s1, s0, s7
	s_wait_alu 0xfffe
	v_add_lshl_u32 v3, s1, v0, 4
	s_wait_loadcnt 0x0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_and_b32_e32 v2, v2, v3
	v_add_nc_u32_e32 v7, 8, v2
	v_lshrrev_b32_e32 v10, 2, v2
	v_add_nc_u32_e32 v5, 4, v2
	s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v11, 31, v10
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v12, vcc, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v13, vcc, s4, v11, vcc
	v_add_co_u32 v14, vcc, v6, v10
	v_lshrrev_b32_e32 v10, 2, v5
	v_add_nc_u32_e32 v2, 12, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v15, vcc, s5, v11, vcc
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_lshrrev_b32_e32 v2, 2, v2
	v_add_co_u32 v16, vcc, v4, v10
	v_ashrrev_i32_e32 v3, 31, v2
	s_delay_alu instid0(VALU_DEP_1)
	v_lshlrev_b64_e64 v[2:3], 4, v[2:3]
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v17, vcc, s4, v11, vcc
	v_add_co_u32 v18, vcc, v6, v10
	v_lshrrev_b32_e32 v10, 2, v7
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v19, vcc, s5, v11, vcc
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v20, vcc, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v21, vcc, s4, v11, vcc
	v_add_co_u32 v22, vcc, v6, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v23, vcc, s5, v11, vcc
	v_add_co_u32 v10, vcc, v4, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v11, vcc, s4, v3, vcc
	v_add_co_u32 v24, vcc, v6, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v25, vcc, s5, v3, vcc
	s_clause 0x7
	global_load_b128 v[28:31], v[12:13], off
	global_load_b128 v[12:15], v[14:15], off
	global_load_b128 v[32:35], v[16:17], off
	global_load_b128 v[16:19], v[18:19], off
	global_load_b128 v[36:39], v[20:21], off
	global_load_b128 v[20:23], v[22:23], off
	global_load_b128 v[40:43], v[10:11], off
	global_load_b128 v[24:27], v[24:25], off
	s_mov_b32 s8, 0x1010101
	s_add_co_u32 s0, s0, 1
	s_wait_loadcnt 0x6
	s_wait_alu 0xfffe
	v_dot4_i32_iu8 v11, v14, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v9, v12, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v10, v13, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
	v_lshlrev_b32_e32 v11, 5, v11
	v_lshlrev_b32_e32 v9, 5, v9
	v_lshlrev_b32_e32 v10, 5, v10
	v_sub_nc_u32_e32 v11, 0, v11
	v_sub_nc_u32_e32 v9, 0, v9
	v_sub_nc_u32_e32 v10, 0, v10
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v14, v14, v30, v11 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v12, v12, v28, v9 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v13, v13, v29, v10 neg_lo:[1,0,0]
	v_add3_u32 v13, v13, v1, v12
	v_dot4_i32_iu8 v12, v15, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b32_e32 v12, 5, v12
	v_sub_nc_u32_e32 v12, 0, v12
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v15, v15, v31, v12 neg_lo:[1,0,0]
	v_add3_u32 v15, v15, v13, v14
	s_wait_loadcnt 0x4
	v_dot4_i32_iu8 v13, v16, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v14, v17, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_lshlrev_b32_e32 v13, 5, v13
	v_lshlrev_b32_e32 v14, 5, v14
	v_sub_nc_u32_e32 v13, 0, v13
	v_sub_nc_u32_e32 v14, 0, v14
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v16, v16, v32, v13 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v17, v17, v33, v14 neg_lo:[1,0,0]
	v_add3_u32 v17, v17, v15, v16
	v_dot4_i32_iu8 v15, v18, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v16, v19, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_lshlrev_b32_e32 v15, 5, v15
	v_lshlrev_b32_e32 v16, 5, v16
	v_sub_nc_u32_e32 v15, 0, v15
	v_sub_nc_u32_e32 v16, 0, v16
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v18, v18, v34, v15 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v19, v19, v35, v16 neg_lo:[1,0,0]
	v_add3_u32 v19, v19, v17, v18
	s_wait_loadcnt 0x2
	v_dot4_i32_iu8 v17, v20, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v18, v21, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_lshlrev_b32_e32 v17, 5, v17
	v_lshlrev_b32_e32 v18, 5, v18
	v_sub_nc_u32_e32 v17, 0, v17
	v_sub_nc_u32_e32 v18, 0, v18
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v20, v20, v36, v17 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v21, v21, v37, v18 neg_lo:[1,0,0]
	v_add3_u32 v21, v21, v19, v20
	v_dot4_i32_iu8 v19, v22, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v20, v23, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_lshlrev_b32_e32 v19, 5, v19
	v_lshlrev_b32_e32 v20, 5, v20
	v_sub_nc_u32_e32 v19, 0, v19
	v_sub_nc_u32_e32 v20, 0, v20
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v22, v22, v38, v19 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v23, v23, v39, v20 neg_lo:[1,0,0]
	v_add3_u32 v23, v23, v21, v22
	s_wait_loadcnt 0x0
	v_dot4_i32_iu8 v21, v24, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v22, v25, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_lshlrev_b32_e32 v21, 5, v21
	v_lshlrev_b32_e32 v22, 5, v22
	v_sub_nc_u32_e32 v21, 0, v21
	v_sub_nc_u32_e32 v22, 0, v22
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v24, v24, v40, v21 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v25, v25, v41, v22 neg_lo:[1,0,0]
	v_add3_u32 v25, v25, v23, v24
	v_dot4_i32_iu8 v23, v26, s8, 0 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v24, v27, s8, 0 neg_lo:[1,0,0]
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_lshlrev_b32_e32 v23, 5, v23
	v_lshlrev_b32_e32 v24, 5, v24
	v_sub_nc_u32_e32 v23, 0, v23
	v_sub_nc_u32_e32 v24, 0, v24
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v26, v26, v42, v23 neg_lo:[1,0,0]
	v_dot4_i32_iu8 v27, v27, v43, v24 neg_lo:[1,0,0]
	v_add3_u32 v1, v27, v25, v26
	s_branch .Lmw_dot_q6_gfx1201_w64_BB2
.Lmw_dot_q6_gfx1201_w64_BB6:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:32
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v2, v2, v0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 2, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v4, vcc, v8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v5, vcc, s6, v3, vcc
	global_load_b32 v3, v[4:5], off
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v3, v3, v1
	global_store_b32 v[4:5], v3, off
.Lmw_dot_q6_gfx1201_w64_BB11:
	s_nop 0
	s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
	s_endpgm)MW"

// dot_q8 gfx1201 w32 vgprs=37 sgprs=128 parsed_max_v=43 parsed_max_s=7 code_size=780 lds=0 scratch=0
#define MICROWAVE_DOT_Q8_GFX1201_W32_BODY R"MW(.Lmw_dot_q8_gfx1201_w32_BB0:
	v_mov_b32_e32 v1, 0
	s_clause 0x1
	global_load_b128 v[4:7], v1, s[2:3]
	global_load_b96 v[8:10], v1, s[2:3] offset:16
	s_mul_i32 s4, ttmp9, s4
	s_delay_alu instid0(SALU_CYCLE_1)
	v_add_nc_u32_e32 v0, s4, v0
	s_wait_loadcnt 0x1
	v_readfirstlane_b32 s1, v5
	v_readfirstlane_b32 s5, v7
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s6, v9
	v_readfirstlane_b32 s7, v10
	v_cmpx_gt_u32_e32 v10, v0
	s_mov_b32 s4, s1
	s_cbranch_execz .Lmw_dot_q8_gfx1201_w32_BB11
.Lmw_dot_q8_gfx1201_w32_BB1:
	v_mov_b32_e32 v1, 0
	s_mov_b32 s0, 0
.Lmw_dot_q8_gfx1201_w32_BB2:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:28
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s1, v2
	s_cmp_ge_u32 s0, s1
	s_cbranch_scc1 .Lmw_dot_q8_gfx1201_w32_BB6
.Lmw_dot_q8_gfx1201_w32_BB5:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:36
	s_mul_i32 s1, s0, s7
	s_wait_alu 0xfffe
	v_add_lshl_u32 v3, s1, v0, 4
	s_wait_loadcnt 0x0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_and_b32_e32 v2, v2, v3
	v_lshrrev_b32_e32 v10, 2, v2
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_ashrrev_i32_e32 v11, 31, v10
	v_add_nc_u32_e32 v5, 4, v2
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v12, vcc_lo, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v13, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v14, vcc_lo, v6, v10
	v_lshrrev_b32_e32 v10, 2, v5
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v15, vcc_lo, s5, v11, vcc_lo
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v20, vcc_lo, v4, v10
	v_add_nc_u32_e32 v7, 8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v21, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v22, vcc_lo, v6, v10
	v_lshrrev_b32_e32 v10, 2, v7
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v23, vcc_lo, s5, v11, vcc_lo
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v28, vcc_lo, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v29, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v30, vcc_lo, v6, v10
	v_add_nc_u32_e32 v2, 12, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v31, vcc_lo, s5, v11, vcc_lo
	v_lshrrev_b32_e32 v2, 2, v2
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 4, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v10, vcc_lo, v4, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v11, vcc_lo, s4, v3, vcc_lo
	v_add_co_u32 v36, vcc_lo, v6, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v37, vcc_lo, s5, v3, vcc_lo
	s_clause 0x7
	global_load_b128 v[16:19], v[12:13], off
	global_load_b128 v[12:15], v[14:15], off
	global_load_b128 v[24:27], v[20:21], off
	global_load_b128 v[20:23], v[22:23], off
	global_load_b128 v[32:35], v[28:29], off
	global_load_b128 v[28:31], v[30:31], off
	global_load_b128 v[40:43], v[10:11], off
	global_load_b128 v[36:39], v[36:37], off
	s_add_co_u32 s0, s0, 1
	s_wait_loadcnt 0x6
	v_dot4_i32_iu8 v16, v16, v12, v1 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v17, v17, v13, v16 neg_lo:[1,1,0]
	v_dot4_i32_iu8 v18, v18, v14, v17 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v19, v19, v15, v18 neg_lo:[1,1,0]
	s_wait_loadcnt 0x4
	v_dot4_i32_iu8 v24, v24, v20, v19 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v25, v25, v21, v24 neg_lo:[1,1,0]
	v_dot4_i32_iu8 v26, v26, v22, v25 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v27, v27, v23, v26 neg_lo:[1,1,0]
	s_wait_loadcnt 0x2
	v_dot4_i32_iu8 v32, v32, v28, v27 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v33, v33, v29, v32 neg_lo:[1,1,0]
	v_dot4_i32_iu8 v34, v34, v30, v33 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v35, v35, v31, v34 neg_lo:[1,1,0]
	s_wait_loadcnt 0x0
	v_dot4_i32_iu8 v40, v40, v36, v35 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v41, v41, v37, v40 neg_lo:[1,1,0]
	v_dot4_i32_iu8 v42, v42, v38, v41 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1)
	v_dot4_i32_iu8 v1, v43, v39, v42 neg_lo:[1,1,0]
	s_branch .Lmw_dot_q8_gfx1201_w32_BB2
.Lmw_dot_q8_gfx1201_w32_BB6:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:32
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v2, v2, v0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 2, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v4, vcc_lo, v8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v5, vcc_lo, s6, v3, vcc_lo
	global_load_b32 v3, v[4:5], off
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v3, v3, v1
	global_store_b32 v[4:5], v3, off
.Lmw_dot_q8_gfx1201_w32_BB11:
	s_nop 0
	s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
	s_endpgm)MW"

// dot_q8 gfx1201 w64 vgprs=37 sgprs=128 parsed_max_v=43 parsed_max_s=7 code_size=776 lds=0 scratch=0
#define MICROWAVE_DOT_Q8_GFX1201_W64_BODY R"MW(.Lmw_dot_q8_gfx1201_w64_BB0:
	v_mov_b32_e32 v1, 0
	s_clause 0x1
	global_load_b128 v[4:7], v1, s[2:3]
	global_load_b96 v[8:10], v1, s[2:3] offset:16
	s_mul_i32 s4, ttmp9, s4
	s_delay_alu instid0(SALU_CYCLE_1)
	v_add_nc_u32_e32 v0, s4, v0
	s_wait_loadcnt 0x1
	v_readfirstlane_b32 s1, v5
	v_readfirstlane_b32 s5, v7
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s6, v9
	v_readfirstlane_b32 s7, v10
	v_cmpx_gt_u32_e32 v10, v0
	s_mov_b32 s4, s1
	s_cbranch_execz .Lmw_dot_q8_gfx1201_w64_BB11
.Lmw_dot_q8_gfx1201_w64_BB1:
	s_mov_b32 s0, 0
	v_mov_b32_e32 v1, 0
.Lmw_dot_q8_gfx1201_w64_BB2:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:28
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s1, v2
	s_cmp_ge_u32 s0, s1
	s_cbranch_scc1 .Lmw_dot_q8_gfx1201_w64_BB6
.Lmw_dot_q8_gfx1201_w64_BB5:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:36
	s_mul_i32 s1, s0, s7
	s_wait_alu 0xfffe
	v_add_lshl_u32 v3, s1, v0, 4
	s_wait_loadcnt 0x0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_and_b32_e32 v2, v2, v3
	v_add_nc_u32_e32 v7, 8, v2
	v_lshrrev_b32_e32 v10, 2, v2
	v_add_nc_u32_e32 v5, 4, v2
	s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v11, 31, v10
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v12, vcc, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v13, vcc, s4, v11, vcc
	v_add_co_u32 v14, vcc, v6, v10
	v_lshrrev_b32_e32 v10, 2, v5
	v_add_nc_u32_e32 v2, 12, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v15, vcc, s5, v11, vcc
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_lshrrev_b32_e32 v2, 2, v2
	v_add_co_u32 v16, vcc, v4, v10
	v_ashrrev_i32_e32 v3, 31, v2
	s_delay_alu instid0(VALU_DEP_1)
	v_lshlrev_b64_e64 v[2:3], 4, v[2:3]
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v17, vcc, s4, v11, vcc
	v_add_co_u32 v18, vcc, v6, v10
	v_lshrrev_b32_e32 v10, 2, v7
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v19, vcc, s5, v11, vcc
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v20, vcc, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v21, vcc, s4, v11, vcc
	v_add_co_u32 v22, vcc, v6, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v23, vcc, s5, v11, vcc
	v_add_co_u32 v10, vcc, v4, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v11, vcc, s4, v3, vcc
	v_add_co_u32 v24, vcc, v6, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v25, vcc, s5, v3, vcc
	s_clause 0x7
	global_load_b128 v[28:31], v[12:13], off
	global_load_b128 v[12:15], v[14:15], off
	global_load_b128 v[32:35], v[16:17], off
	global_load_b128 v[16:19], v[18:19], off
	global_load_b128 v[36:39], v[20:21], off
	global_load_b128 v[20:23], v[22:23], off
	global_load_b128 v[40:43], v[10:11], off
	global_load_b128 v[24:27], v[24:25], off
	s_add_co_u32 s0, s0, 1
	s_wait_loadcnt 0x6
	v_dot4_i32_iu8 v28, v28, v12, v1 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v29, v29, v13, v28 neg_lo:[1,1,0]
	v_dot4_i32_iu8 v30, v30, v14, v29 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v31, v31, v15, v30 neg_lo:[1,1,0]
	s_wait_loadcnt 0x4
	v_dot4_i32_iu8 v32, v32, v16, v31 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v33, v33, v17, v32 neg_lo:[1,1,0]
	v_dot4_i32_iu8 v34, v34, v18, v33 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v35, v35, v19, v34 neg_lo:[1,1,0]
	s_wait_loadcnt 0x2
	v_dot4_i32_iu8 v36, v36, v20, v35 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v37, v37, v21, v36 neg_lo:[1,1,0]
	v_dot4_i32_iu8 v38, v38, v22, v37 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v39, v39, v23, v38 neg_lo:[1,1,0]
	s_wait_loadcnt 0x0
	v_dot4_i32_iu8 v40, v40, v24, v39 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_dot4_i32_iu8 v41, v41, v25, v40 neg_lo:[1,1,0]
	v_dot4_i32_iu8 v42, v42, v26, v41 neg_lo:[1,1,0]
	s_delay_alu instid0(VALU_DEP_1)
	v_dot4_i32_iu8 v1, v43, v27, v42 neg_lo:[1,1,0]
	s_branch .Lmw_dot_q8_gfx1201_w64_BB2
.Lmw_dot_q8_gfx1201_w64_BB6:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:32
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v2, v2, v0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 2, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v4, vcc, v8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v5, vcc, s6, v3, vcc
	global_load_b32 v3, v[4:5], off
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v3, v3, v1
	global_store_b32 v[4:5], v3, off
.Lmw_dot_q8_gfx1201_w64_BB11:
	s_nop 0
	s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
	s_endpgm)MW"

// dot_scalar gfx1201 w32 vgprs=41 sgprs=128 parsed_max_v=95 parsed_max_s=9 code_size=3688 lds=0 scratch=0
#define MICROWAVE_DOT_SCALAR_GFX1201_W32_BODY R"MW(.Lmw_dot_scalar_gfx1201_w32_BB0:
	v_mov_b32_e32 v1, 0
	s_clause 0x1
	global_load_b128 v[4:7], v1, s[2:3]
	global_load_b96 v[8:10], v1, s[2:3] offset:16
	s_mul_i32 s4, ttmp9, s4
	s_delay_alu instid0(SALU_CYCLE_1)
	v_add_nc_u32_e32 v0, s4, v0
	s_wait_loadcnt 0x1
	v_readfirstlane_b32 s1, v5
	v_readfirstlane_b32 s5, v7
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s6, v9
	v_readfirstlane_b32 s7, v10
	v_cmpx_gt_u32_e32 v10, v0
	s_mov_b32 s4, s1
	s_cbranch_execz .Lmw_dot_scalar_gfx1201_w32_BB11
.Lmw_dot_scalar_gfx1201_w32_BB1:
	v_mov_b32_e32 v1, 0
	s_mov_b32 s0, 0
.Lmw_dot_scalar_gfx1201_w32_BB2:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:28
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s1, v2
	s_cmp_ge_u32 s0, s1
	s_cbranch_scc1 .Lmw_dot_scalar_gfx1201_w32_BB6
.Lmw_dot_scalar_gfx1201_w32_BB5:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:36
	s_mul_i32 s1, s0, s7
	s_wait_alu 0xfffe
	v_add_lshl_u32 v3, s1, v0, 4
	s_wait_loadcnt 0x0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_and_b32_e32 v2, v2, v3
	v_lshrrev_b32_e32 v10, 2, v2
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_ashrrev_i32_e32 v11, 31, v10
	v_add_nc_u32_e32 v5, 4, v2
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v12, vcc_lo, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v13, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v14, vcc_lo, v6, v10
	v_lshrrev_b32_e32 v10, 2, v5
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v15, vcc_lo, s5, v11, vcc_lo
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v20, vcc_lo, v4, v10
	v_add_nc_u32_e32 v7, 8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v21, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v22, vcc_lo, v6, v10
	v_lshrrev_b32_e32 v10, 2, v7
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v23, vcc_lo, s5, v11, vcc_lo
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v28, vcc_lo, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v29, vcc_lo, s4, v11, vcc_lo
	v_add_co_u32 v30, vcc_lo, v6, v10
	v_add_nc_u32_e32 v2, 12, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v31, vcc_lo, s5, v11, vcc_lo
	v_lshrrev_b32_e32 v2, 2, v2
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 4, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v10, vcc_lo, v4, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v11, vcc_lo, s4, v3, vcc_lo
	v_add_co_u32 v36, vcc_lo, v6, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v37, vcc_lo, s5, v3, vcc_lo
	s_clause 0x7
	global_load_b128 v[16:19], v[12:13], off
	global_load_b128 v[12:15], v[14:15], off
	global_load_b128 v[24:27], v[20:21], off
	global_load_b128 v[20:23], v[22:23], off
	global_load_b128 v[32:35], v[28:29], off
	global_load_b128 v[28:31], v[30:31], off
	global_load_b128 v[40:43], v[10:11], off
	global_load_b128 v[36:39], v[36:37], off
	s_movk_i32 s8, 0xff00
	s_movk_i32 s9, 0x80
	s_add_co_u32 s0, s0, 1
	s_wait_loadcnt 0x7
	v_and_b32_e32 v9, 15, v16
	v_bfe_u32 v46, v17, 16, 4
	v_bfe_u32 v10, v16, 8, 4
	v_bfe_u32 v45, v17, 8, 4
	v_bfe_u32 v11, v16, 16, 4
	v_bfe_u32 v16, v16, 24, 4
	v_and_b32_e32 v44, 15, v17
	v_bfe_u32 v17, v17, 24, 4
	v_and_b32_e32 v47, 15, v18
	v_bfe_u32 v48, v18, 8, 4
	v_bfe_u32 v49, v18, 16, 4
	v_add_nc_u32_e32 v9, -8, v9
	v_add_nc_u32_e32 v46, -8, v46
	v_bfe_u32 v18, v18, 24, 4
	v_add_nc_u32_e32 v10, -8, v10
	v_and_b32_e32 v50, 15, v19
	v_add_nc_u32_e32 v45, -8, v45
	v_add_nc_u32_e32 v11, -8, v11
	v_bfe_u32 v51, v19, 8, 4
	v_add_nc_u32_e32 v16, -8, v16
	v_add_nc_u32_e32 v44, -8, v44
	v_add_nc_u32_e32 v17, -8, v17
	v_bfe_u32 v52, v19, 16, 4
	v_add_nc_u32_e32 v47, -8, v47
	v_bfe_u32 v19, v19, 24, 4
	v_add_nc_u32_e32 v48, -8, v48
	s_wait_loadcnt 0x6
	v_bfe_u32 v53, v12, 0, 8
	v_add_nc_u32_e32 v49, -8, v49
	v_add_nc_u32_e32 v18, -8, v18
	v_bfe_u32 v55, v12, 8, 8
	v_add_nc_u32_e32 v50, -8, v50
	v_bfe_u32 v57, v12, 16, 8
	v_add_nc_u32_e32 v51, -8, v51
	v_lshrrev_b32_e32 v12, 24, v12
	v_bfe_u32 v60, v13, 0, 8
	v_add_nc_u32_e32 v19, -8, v19
	s_wait_alu 0xfffe
	v_cmp_le_i32_e32 vcc_lo, s9, v53
	v_add_nc_u32_e32 v54, s8, v53
	v_bfe_u32 v62, v13, 8, 8
	v_bfe_u32 v64, v13, 16, 8
	v_add_nc_u32_e32 v59, s8, v12
	s_wait_alu 0xfffd
	s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_dual_cndmask_b32 v53, v53, v54 :: v_dual_add_nc_u32 v56, s8, v55
	v_cmp_le_i32_e32 vcc_lo, s9, v55
	v_mul_lo_u32 v9, v9, v53
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v55, v55, v56 :: v_dual_add_nc_u32 v58, s8, v57
	v_cmp_le_i32_e32 vcc_lo, s9, v57
	v_bfe_u32 v67, v14, 0, 8
	v_bfe_u32 v69, v14, 8, 8
	v_bfe_u32 v71, v14, 16, 8
	v_lshrrev_b32_e32 v14, 24, v14
	v_lshrrev_b32_e32 v13, 24, v13
	v_mul_lo_u32 v10, v10, v55
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v57, v57, v58 :: v_dual_add_nc_u32 v52, -8, v52
	v_cmp_le_i32_e32 vcc_lo, s9, v12
	v_add_nc_u32_e32 v68, s8, v67
	v_add_nc_u32_e32 v66, s8, v13
	s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_2)
	v_mul_lo_u32 v11, v11, v57
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v12, v12, v59 :: v_dual_add_nc_u32 v61, s8, v60
	v_cmp_le_i32_e32 vcc_lo, s9, v60
	v_mul_lo_u32 v16, v16, v12
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v60, v60, v61 :: v_dual_add_nc_u32 v63, s8, v62
	v_cmp_le_i32_e32 vcc_lo, s9, v62
	v_add3_u32 v11, v11, v9, v10
	v_bfe_u32 v74, v15, 0, 8
	v_bfe_u32 v76, v15, 8, 8
	v_bfe_u32 v78, v15, 16, 8
	v_mul_lo_u32 v44, v44, v60
	v_lshrrev_b32_e32 v15, 24, v15
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v62, v62, v63 :: v_dual_add_nc_u32 v65, s8, v64
	v_cmp_le_i32_e32 vcc_lo, s9, v64
	v_add3_u32 v1, v1, v11, v16
	s_wait_loadcnt 0x5
	v_bfe_u32 v82, v24, 8, 4
	v_add_nc_u32_e32 v75, s8, v74
	v_add_nc_u32_e32 v77, s8, v76
	v_mul_lo_u32 v45, v45, v62
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v64, v64, v65 :: v_dual_add_nc_u32 v73, s8, v14
	v_cmp_le_i32_e32 vcc_lo, s9, v13
	v_add_nc_u32_e32 v79, s8, v78
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_4) | instid1(VALU_DEP_3)
	v_mul_lo_u32 v46, v46, v64
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v13, v13, v66 :: v_dual_add_nc_u32 v70, s8, v69
	v_cmp_le_i32_e32 vcc_lo, s9, v67
	v_bfe_u32 v83, v24, 16, 4
	v_mul_lo_u32 v17, v17, v13
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v67, v67, v68 :: v_dual_add_nc_u32 v72, s8, v71
	v_cmp_le_i32_e32 vcc_lo, s9, v69
	v_add3_u32 v46, v46, v44, v45
	s_delay_alu instid0(VALU_DEP_3)
	v_mul_lo_u32 v47, v47, v67
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v69, v69, v70 :: v_dual_add_nc_u32 v80, s8, v15
	v_cmp_le_i32_e32 vcc_lo, s9, v71
	v_add3_u32 v1, v1, v46, v17
	v_and_b32_e32 v84, 15, v25
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v48, v48, v69
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v71, v71, v72 :: v_dual_add_nc_u32 v82, -8, v82
	v_cmp_le_i32_e32 vcc_lo, s9, v14
	v_bfe_u32 v85, v25, 8, 4
	v_add_nc_u32_e32 v84, -8, v84
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v49, v49, v71
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v14, v14, v73 :: v_dual_and_b32 v81, 15, v24
	v_bfe_u32 v24, v24, 24, 4
	v_cmp_le_i32_e32 vcc_lo, s9, v74
	v_bfe_u32 v86, v25, 16, 4
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v18, v18, v14
	v_add_nc_u32_e32 v24, -8, v24
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v74, v74, v75 :: v_dual_add_nc_u32 v81, -8, v81
	v_cmp_le_i32_e32 vcc_lo, s9, v76
	v_add3_u32 v49, v49, v47, v48
	v_bfe_u32 v25, v25, 24, 4
	v_and_b32_e32 v87, 15, v26
	v_bfe_u32 v88, v26, 8, 4
	v_bfe_u32 v89, v26, 16, 4
	v_mul_lo_u32 v50, v50, v74
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v76, v76, v77 :: v_dual_add_nc_u32 v83, -8, v83
	v_cmp_le_i32_e32 vcc_lo, s9, v78
	v_add3_u32 v1, v1, v49, v18
	v_add_nc_u32_e32 v25, -8, v25
	v_add_nc_u32_e32 v87, -8, v87
	v_add_nc_u32_e32 v88, -8, v88
	v_bfe_u32 v26, v26, 24, 4
	v_add_nc_u32_e32 v89, -8, v89
	v_and_b32_e32 v90, 15, v27
	v_bfe_u32 v91, v27, 8, 4
	s_wait_loadcnt 0x4
	v_bfe_u32 v93, v20, 0, 8
	v_mul_lo_u32 v51, v51, v76
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v78, v78, v79 :: v_dual_add_nc_u32 v85, -8, v85
	v_cmp_le_i32_e32 vcc_lo, s9, v15
	v_bfe_u32 v92, v27, 16, 4
	v_bfe_u32 v27, v27, 24, 4
	v_bfe_u32 v95, v20, 8, 8
	v_add_nc_u32_e32 v26, -8, v26
	v_add_nc_u32_e32 v91, -8, v91
	v_add_nc_u32_e32 v94, s8, v93
	v_add_nc_u32_e32 v90, -8, v90
	v_bfe_u32 v3, v20, 16, 8
	v_mul_lo_u32 v52, v52, v78
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v15, v15, v80 :: v_dual_add_nc_u32 v86, -8, v86
	v_cmp_le_i32_e32 vcc_lo, s9, v93
	v_lshrrev_b32_e32 v20, 24, v20
	v_add_nc_u32_e32 v27, -8, v27
	v_bfe_u32 v9, v21, 0, 8
	v_add_nc_u32_e32 v5, s8, v3
	v_bfe_u32 v11, v21, 8, 8
	v_mul_lo_u32 v19, v19, v15
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v93, v93, v94 :: v_dual_add_nc_u32 v2, s8, v95
	v_cmp_le_i32_e32 vcc_lo, s9, v95
	v_add3_u32 v52, v52, v50, v51
	v_add_nc_u32_e32 v7, s8, v20
	v_add_nc_u32_e32 v10, s8, v9
	v_bfe_u32 v13, v21, 16, 8
	v_mul_lo_u32 v81, v81, v93
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v95, v95, v2, vcc_lo
	v_cmp_le_i32_e32 vcc_lo, s9, v3
	v_add3_u32 v1, v1, v52, v19
	v_lshrrev_b32_e32 v21, 24, v21
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v82, v82, v95
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v3, v3, v5 :: v_dual_add_nc_u32 v92, -8, v92
	v_cmp_le_i32_e32 vcc_lo, s9, v20
	v_add_nc_u32_e32 v15, s8, v21
	v_bfe_u32 v16, v22, 0, 8
	v_bfe_u32 v18, v22, 8, 8
	v_mul_lo_u32 v83, v83, v3
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v20, v20, v7, vcc_lo
	v_cmp_le_i32_e32 vcc_lo, s9, v9
	v_add_nc_u32_e32 v17, s8, v16
	s_delay_alu instid0(VALU_DEP_3)
	v_mul_lo_u32 v24, v24, v20
	v_bfe_u32 v20, v22, 16, 8
	v_lshrrev_b32_e32 v22, 24, v22
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v9, v9, v10 :: v_dual_add_nc_u32 v12, s8, v11
	v_cmp_le_i32_e32 vcc_lo, s9, v11
	v_add3_u32 v83, v83, v81, v82
	s_delay_alu instid0(VALU_DEP_3)
	v_mul_lo_u32 v84, v84, v9
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v11, v11, v12 :: v_dual_add_nc_u32 v14, s8, v13
	v_cmp_le_i32_e32 vcc_lo, s9, v13
	v_add3_u32 v1, v1, v83, v24
	v_bfe_u32 v44, v23, 8, 8
	s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_3)
	v_mul_lo_u32 v85, v85, v11
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v13, v13, v14, vcc_lo
	v_cmp_le_i32_e32 vcc_lo, s9, v21
	v_bfe_u32 v46, v23, 16, 8
	v_mul_lo_u32 v86, v86, v13
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v21, v21, v15 :: v_dual_add_nc_u32 v24, s8, v22
	v_cmp_le_i32_e32 vcc_lo, s9, v16
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_4) | instid1(VALU_DEP_3)
	v_mul_lo_u32 v25, v25, v21
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v16, v16, v17 :: v_dual_add_nc_u32 v19, s8, v18
	v_cmp_le_i32_e32 vcc_lo, s9, v18
	v_add3_u32 v86, v86, v84, v85
	v_mul_lo_u32 v87, v87, v16
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v18, v18, v19 :: v_dual_add_nc_u32 v21, s8, v20
	v_cmp_le_i32_e32 vcc_lo, s9, v20
	v_add3_u32 v1, v1, v86, v25
	v_bfe_u32 v25, v23, 0, 8
	v_lshrrev_b32_e32 v23, 24, v23
	s_wait_loadcnt 0x2
	v_bfe_u32 v49, v28, 0, 8
	v_bfe_u32 v52, v28, 8, 8
	v_mul_lo_u32 v88, v88, v18
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v20, v20, v21 :: v_dual_add_nc_u32 v45, s8, v44
	v_cmp_le_i32_e32 vcc_lo, s9, v22
	v_add_nc_u32_e32 v48, s8, v23
	v_bfe_u32 v55, v28, 16, 8
	s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_3)
	v_mul_lo_u32 v89, v89, v20
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v22, v22, v24 :: v_dual_add_nc_u32 v47, s8, v46
	v_cmp_le_i32_e32 vcc_lo, s9, v25
	v_lshrrev_b32_e32 v28, 24, v28
	v_mul_lo_u32 v26, v26, v22
	v_add3_u32 v89, v89, v87, v88
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
	v_add3_u32 v1, v1, v89, v26
	v_add_nc_u32_e32 v26, s8, v25
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v25, v25, v26 :: v_dual_add_nc_u32 v50, s8, v49
	v_cmp_le_i32_e32 vcc_lo, s9, v44
	v_bfe_u32 v54, v32, 8, 4
	s_delay_alu instid0(VALU_DEP_3)
	v_mul_lo_u32 v90, v90, v25
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v44, v44, v45 :: v_dual_and_b32 v51, 15, v32
	v_cmp_le_i32_e32 vcc_lo, s9, v46
	v_bfe_u32 v57, v32, 16, 4
	v_and_b32_e32 v61, 15, v33
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v91, v91, v44
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v46, v46, v47 :: v_dual_add_nc_u32 v53, s8, v52
	v_cmp_le_i32_e32 vcc_lo, s9, v23
	v_add_nc_u32_e32 v57, -8, v57
	v_bfe_u32 v32, v32, 24, 4
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v92, v92, v46
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v23, v23, v48 :: v_dual_add_nc_u32 v56, s8, v55
	v_cmp_le_i32_e32 vcc_lo, s9, v49
	v_add_nc_u32_e32 v32, -8, v32
	v_bfe_u32 v59, v29, 0, 8
	v_bfe_u32 v62, v29, 8, 8
	v_bfe_u32 v64, v33, 8, 4
	v_mul_lo_u32 v27, v27, v23
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v49, v49, v50 :: v_dual_add_nc_u32 v58, s8, v28
	v_cmp_le_i32_e32 vcc_lo, s9, v52
	v_add3_u32 v92, v92, v90, v91
	v_add_nc_u32_e32 v60, s8, v59
	v_add_nc_u32_e32 v63, s8, v62
	v_bfe_u32 v65, v29, 16, 8
	v_add_nc_u32_e32 v64, -8, v64
	v_lshrrev_b32_e32 v29, 24, v29
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v52, v52, v53 :: v_dual_add_nc_u32 v51, -8, v51
	v_cmp_le_i32_e32 vcc_lo, s9, v55
	v_add3_u32 v1, v1, v92, v27
	v_bfe_u32 v67, v33, 16, 4
	v_bfe_u32 v33, v33, 24, 4
	v_add_nc_u32_e32 v66, s8, v65
	v_mul_lo_u32 v51, v51, v49
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v55, v55, v56 :: v_dual_add_nc_u32 v54, -8, v54
	v_cmp_le_i32_e32 vcc_lo, s9, v28
	v_add_nc_u32_e32 v67, -8, v67
	v_bfe_u32 v69, v30, 0, 8
	v_bfe_u32 v74, v34, 8, 4
	v_mul_lo_u32 v54, v54, v52
	v_mul_lo_u32 v57, v57, v55
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v28, v28, v58 :: v_dual_add_nc_u32 v61, -8, v61
	v_cmp_le_i32_e32 vcc_lo, s9, v59
	v_bfe_u32 v75, v30, 16, 8
	v_and_b32_e32 v71, 15, v34
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v32, v32, v28
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v59, v59, v60 :: v_dual_add_nc_u32 v68, s8, v29
	v_cmp_le_i32_e32 vcc_lo, s9, v62
	v_add3_u32 v57, v57, v51, v54
	v_bfe_u32 v72, v30, 8, 8
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v61, v61, v59
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v62, v62, v63 :: v_dual_add_nc_u32 v33, -8, v33
	v_cmp_le_i32_e32 vcc_lo, s9, v65
	v_add3_u32 v1, v1, v57, v32
	v_add_nc_u32_e32 v73, s8, v72
	v_lshrrev_b32_e32 v30, 24, v30
	v_bfe_u32 v77, v34, 16, 4
	v_mul_lo_u32 v64, v64, v62
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v65, v65, v66 :: v_dual_add_nc_u32 v70, s8, v69
	v_cmp_le_i32_e32 vcc_lo, s9, v29
	v_add_nc_u32_e32 v77, -8, v77
	v_bfe_u32 v79, v31, 0, 8
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v67, v67, v65
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v29, v29, v68 :: v_dual_add_nc_u32 v74, -8, v74
	v_cmp_le_i32_e32 vcc_lo, s9, v69
	v_add_nc_u32_e32 v80, s8, v79
	v_bfe_u32 v34, v34, 24, 4
	v_bfe_u32 v82, v31, 8, 8
	v_mul_lo_u32 v33, v33, v29
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v69, v69, v70 :: v_dual_add_nc_u32 v76, s8, v75
	v_cmp_le_i32_e32 vcc_lo, s9, v72
	v_add3_u32 v67, v67, v61, v64
	v_add_nc_u32_e32 v83, s8, v82
	v_bfe_u32 v84, v35, 8, 4
	v_bfe_u32 v85, v31, 16, 8
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v72, v72, v73 :: v_dual_add_nc_u32 v71, -8, v71
	v_cmp_le_i32_e32 vcc_lo, s9, v75
	v_add3_u32 v1, v1, v67, v33
	v_lshrrev_b32_e32 v31, 24, v31
	v_add_nc_u32_e32 v84, -8, v84
	v_add_nc_u32_e32 v86, s8, v85
	v_bfe_u32 v87, v35, 16, 4
	v_mul_lo_u32 v71, v71, v69
	v_mul_lo_u32 v74, v74, v72
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v75, v75, v76 :: v_dual_add_nc_u32 v78, s8, v30
	v_cmp_le_i32_e32 vcc_lo, s9, v30
	v_add_nc_u32_e32 v88, s8, v31
	v_add_nc_u32_e32 v87, -8, v87
	s_wait_loadcnt 0x0
	v_bfe_u32 v89, v36, 0, 8
	v_mul_lo_u32 v77, v77, v75
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v30, v30, v78 :: v_dual_and_b32 v81, 15, v35
	v_cmp_le_i32_e32 vcc_lo, s9, v79
	v_bfe_u32 v35, v35, 24, 4
	v_bfe_u32 v94, v40, 8, 4
	v_bfe_u32 v95, v36, 16, 8
	v_and_b32_e32 v91, 15, v40
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v79, v79, v80 :: v_dual_add_nc_u32 v34, -8, v34
	v_cmp_le_i32_e32 vcc_lo, s9, v82
	v_add3_u32 v77, v77, v71, v74
	v_add_nc_u32_e32 v35, -8, v35
	v_bfe_u32 v92, v36, 8, 8
	v_add_nc_u32_e32 v91, -8, v91
	v_bfe_u32 v3, v40, 16, 4
	v_mul_lo_u32 v34, v34, v30
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v82, v82, v83 :: v_dual_add_nc_u32 v81, -8, v81
	v_cmp_le_i32_e32 vcc_lo, s9, v85
	v_add_nc_u32_e32 v93, s8, v92
	v_add_nc_u32_e32 v3, -8, v3
	v_lshrrev_b32_e32 v36, 24, v36
	v_mul_lo_u32 v84, v84, v82
	v_mul_lo_u32 v81, v81, v79
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v85, v85, v86 :: v_dual_add_nc_u32 v90, s8, v89
	v_cmp_le_i32_e32 vcc_lo, s9, v31
	v_add3_u32 v1, v1, v77, v34
	v_bfe_u32 v40, v40, 24, 4
	v_bfe_u32 v7, v37, 0, 8
	v_and_b32_e32 v10, 15, v41
	v_mul_lo_u32 v87, v87, v85
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v31, v31, v88 :: v_dual_add_nc_u32 v94, -8, v94
	v_cmp_le_i32_e32 vcc_lo, s9, v89
	v_bfe_u32 v11, v37, 8, 8
	v_bfe_u32 v13, v41, 8, 4
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v35, v35, v31
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v89, v89, v90 :: v_dual_add_nc_u32 v2, s8, v95
	v_cmp_le_i32_e32 vcc_lo, s9, v92
	v_add3_u32 v87, v87, v81, v84
	v_add_nc_u32_e32 v13, -8, v13
	v_bfe_u32 v14, v37, 16, 8
	v_mul_lo_u32 v91, v91, v89
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v92, v92, v93 :: v_dual_add_nc_u32 v5, s8, v36
	v_cmp_le_i32_e32 vcc_lo, s9, v95
	v_add3_u32 v1, v1, v87, v35
	v_add_nc_u32_e32 v15, s8, v14
	v_lshrrev_b32_e32 v37, 24, v37
	v_bfe_u32 v16, v41, 16, 4
	v_mul_lo_u32 v94, v94, v92
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v95, v95, v2 :: v_dual_add_nc_u32 v40, -8, v40
	v_cmp_le_i32_e32 vcc_lo, s9, v36
	v_add_nc_u32_e32 v16, -8, v16
	v_bfe_u32 v18, v38, 0, 8
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v3, v3, v95
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v36, v36, v5 :: v_dual_add_nc_u32 v9, s8, v7
	v_cmp_le_i32_e32 vcc_lo, s9, v7
	v_add_nc_u32_e32 v19, s8, v18
	v_bfe_u32 v41, v41, 24, 4
	v_bfe_u32 v21, v38, 8, 8
	v_mul_lo_u32 v40, v40, v36
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v7, v7, v9 :: v_dual_add_nc_u32 v12, s8, v11
	v_cmp_le_i32_e32 vcc_lo, s9, v11
	v_add3_u32 v3, v3, v91, v94
	v_add_nc_u32_e32 v22, s8, v21
	v_bfe_u32 v23, v42, 8, 4
	v_bfe_u32 v24, v38, 16, 8
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v11, v11, v12 :: v_dual_add_nc_u32 v10, -8, v10
	v_cmp_le_i32_e32 vcc_lo, s9, v14
	v_add3_u32 v1, v1, v3, v40
	v_add_nc_u32_e32 v23, -8, v23
	v_lshrrev_b32_e32 v38, 24, v38
	v_add_nc_u32_e32 v25, s8, v24
	v_bfe_u32 v26, v42, 16, 4
	v_mul_lo_u32 v13, v13, v11
	v_mul_lo_u32 v10, v10, v7
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v14, v14, v15 :: v_dual_add_nc_u32 v17, s8, v37
	v_cmp_le_i32_e32 vcc_lo, s9, v37
	v_add_nc_u32_e32 v27, s8, v38
	v_add_nc_u32_e32 v26, -8, v26
	v_bfe_u32 v28, v39, 0, 8
	v_mul_lo_u32 v16, v16, v14
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v37, v37, v17 :: v_dual_and_b32 v20, 15, v42
	v_cmp_le_i32_e32 vcc_lo, s9, v18
	v_bfe_u32 v42, v42, 24, 4
	v_bfe_u32 v34, v39, 16, 8
	v_and_b32_e32 v30, 15, v43
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v18, v18, v19 :: v_dual_add_nc_u32 v41, -8, v41
	v_cmp_le_i32_e32 vcc_lo, s9, v21
	v_add_nc_u32_e32 v42, -8, v42
	v_add3_u32 v16, v16, v10, v13
	v_bfe_u32 v31, v39, 8, 8
	v_lshrrev_b32_e32 v39, 24, v39
	v_mul_lo_u32 v41, v41, v37
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v21, v21, v22 :: v_dual_add_nc_u32 v20, -8, v20
	v_cmp_le_i32_e32 vcc_lo, s9, v24
	v_add_nc_u32_e32 v32, s8, v31
	v_bfe_u32 v33, v43, 8, 4
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v23, v23, v21
	v_mul_lo_u32 v20, v20, v18
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v24, v24, v25 :: v_dual_add_nc_u32 v29, s8, v28
	v_cmp_le_i32_e32 vcc_lo, s9, v38
	v_add3_u32 v1, v1, v16, v41
	v_bfe_u32 v36, v43, 16, 4
	v_bfe_u32 v43, v43, 24, 4
	v_mul_lo_u32 v26, v26, v24
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v38, v38, v27 :: v_dual_add_nc_u32 v35, s8, v34
	v_cmp_le_i32_e32 vcc_lo, s9, v28
	v_add_nc_u32_e32 v43, -8, v43
	s_delay_alu instid0(VALU_DEP_3)
	v_mul_lo_u32 v42, v42, v38
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v28, v28, v29 :: v_dual_add_nc_u32 v37, s8, v39
	v_cmp_le_i32_e32 vcc_lo, s9, v31
	v_add3_u32 v26, v26, v20, v23
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v31, v31, v32 :: v_dual_add_nc_u32 v30, -8, v30
	v_cmp_le_i32_e32 vcc_lo, s9, v34
	v_add3_u32 v1, v1, v26, v42
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_2)
	v_mul_lo_u32 v30, v30, v28
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v34, v34, v35 :: v_dual_add_nc_u32 v33, -8, v33
	v_cmp_le_i32_e32 vcc_lo, s9, v39
	v_mul_lo_u32 v33, v33, v31
	s_wait_alu 0xfffd
	v_dual_cndmask_b32 v39, v39, v37 :: v_dual_add_nc_u32 v36, -8, v36
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
	v_mul_lo_u32 v36, v36, v34
	v_mul_lo_u32 v43, v43, v39
	v_add3_u32 v36, v36, v30, v33
	v_add3_u32 v1, v1, v36, v43
	s_branch .Lmw_dot_scalar_gfx1201_w32_BB2
.Lmw_dot_scalar_gfx1201_w32_BB6:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:32
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v2, v2, v0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 2, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v4, vcc_lo, v8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v5, vcc_lo, s6, v3, vcc_lo
	global_load_b32 v3, v[4:5], off
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v3, v3, v1
	global_store_b32 v[4:5], v3, off
.Lmw_dot_scalar_gfx1201_w32_BB11:
	s_nop 0
	s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
	s_endpgm)MW"

// dot_scalar gfx1201 w64 vgprs=41 sgprs=128 parsed_max_v=47 parsed_max_s=9 code_size=3672 lds=0 scratch=0
#define MICROWAVE_DOT_SCALAR_GFX1201_W64_BODY R"MW(.Lmw_dot_scalar_gfx1201_w64_BB0:
	v_mov_b32_e32 v1, 0
	s_clause 0x1
	global_load_b128 v[4:7], v1, s[2:3]
	global_load_b96 v[8:10], v1, s[2:3] offset:16
	s_mul_i32 s4, ttmp9, s4
	s_delay_alu instid0(SALU_CYCLE_1)
	v_add_nc_u32_e32 v0, s4, v0
	s_wait_loadcnt 0x1
	v_readfirstlane_b32 s1, v5
	v_readfirstlane_b32 s5, v7
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s6, v9
	v_readfirstlane_b32 s7, v10
	v_cmpx_gt_u32_e32 v10, v0
	s_mov_b32 s4, s1
	s_cbranch_execz .Lmw_dot_scalar_gfx1201_w64_BB11
.Lmw_dot_scalar_gfx1201_w64_BB1:
	s_mov_b32 s0, 0
	v_mov_b32_e32 v1, 0
.Lmw_dot_scalar_gfx1201_w64_BB2:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:28
	s_wait_loadcnt 0x0
	v_readfirstlane_b32 s1, v2
	s_cmp_ge_u32 s0, s1
	s_cbranch_scc1 .Lmw_dot_scalar_gfx1201_w64_BB6
.Lmw_dot_scalar_gfx1201_w64_BB5:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:36
	s_mul_i32 s1, s0, s7
	s_wait_alu 0xfffe
	v_add_lshl_u32 v3, s1, v0, 4
	s_wait_loadcnt 0x0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_and_b32_e32 v2, v2, v3
	v_add_nc_u32_e32 v7, 8, v2
	v_lshrrev_b32_e32 v10, 2, v2
	v_add_nc_u32_e32 v5, 4, v2
	s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v11, 31, v10
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v12, vcc, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v13, vcc, s4, v11, vcc
	v_add_co_u32 v14, vcc, v6, v10
	v_lshrrev_b32_e32 v10, 2, v5
	v_add_nc_u32_e32 v2, 12, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v15, vcc, s5, v11, vcc
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_lshrrev_b32_e32 v2, 2, v2
	v_add_co_u32 v16, vcc, v4, v10
	v_ashrrev_i32_e32 v3, 31, v2
	s_delay_alu instid0(VALU_DEP_1)
	v_lshlrev_b64_e64 v[2:3], 4, v[2:3]
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v17, vcc, s4, v11, vcc
	v_add_co_u32 v18, vcc, v6, v10
	v_lshrrev_b32_e32 v10, 2, v7
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v19, vcc, s5, v11, vcc
	v_ashrrev_i32_e32 v11, 31, v10
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_lshlrev_b64_e64 v[10:11], 4, v[10:11]
	v_add_co_u32 v20, vcc, v4, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v21, vcc, s4, v11, vcc
	v_add_co_u32 v22, vcc, v6, v10
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v23, vcc, s5, v11, vcc
	v_add_co_u32 v10, vcc, v4, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v11, vcc, s4, v3, vcc
	v_add_co_u32 v24, vcc, v6, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v25, vcc, s5, v3, vcc
	s_clause 0x7
	global_load_b128 v[28:31], v[12:13], off
	global_load_b128 v[12:15], v[14:15], off
	global_load_b128 v[32:35], v[16:17], off
	global_load_b128 v[16:19], v[18:19], off
	global_load_b128 v[36:39], v[20:21], off
	global_load_b128 v[20:23], v[22:23], off
	global_load_b128 v[40:43], v[10:11], off
	global_load_b128 v[24:27], v[24:25], off
	s_movk_i32 s8, 0xff00
	s_movk_i32 s9, 0x80
	s_add_co_u32 s0, s0, 1
	s_wait_loadcnt 0x7
	v_bfe_u32 v11, v28, 16, 4
	v_and_b32_e32 v44, 15, v29
	v_bfe_u32 v45, v29, 8, 4
	v_and_b32_e32 v9, 15, v28
	v_bfe_u32 v46, v29, 16, 4
	v_bfe_u32 v29, v29, 24, 4
	v_bfe_u32 v10, v28, 8, 4
	v_bfe_u32 v28, v28, 24, 4
	v_and_b32_e32 v47, 15, v30
	s_wait_loadcnt 0x6
	v_bfe_u32 v2, v12, 0, 8
	v_add_nc_u32_e32 v11, -8, v11
	v_add_nc_u32_e32 v44, -8, v44
	v_add_nc_u32_e32 v45, -8, v45
	v_bfe_u32 v5, v12, 8, 8
	v_add_nc_u32_e32 v9, -8, v9
	v_add_nc_u32_e32 v46, -8, v46
	v_add_nc_u32_e32 v29, -8, v29
	v_add_nc_u32_e32 v10, -8, v10
	v_add_nc_u32_e32 v28, -8, v28
	v_add_nc_u32_e32 v47, -8, v47
	s_wait_alu 0xfffe
	v_add_nc_u32_e32 v3, s8, v2
	v_cmp_le_i32_e32 vcc, s9, v2
	v_add_nc_u32_e32 v7, s8, v5
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v2, v2, v3, vcc
	v_cmp_le_i32_e32 vcc, s9, v5
	s_delay_alu instid0(VALU_DEP_2)
	v_mul_lo_u32 v9, v9, v2
	v_bfe_u32 v2, v12, 16, 8
	v_lshrrev_b32_e32 v12, 24, v12
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v5, v5, v7, vcc
	v_bfe_u32 v7, v13, 0, 8
	s_delay_alu instid0(VALU_DEP_4)
	v_add_nc_u32_e32 v3, s8, v2
	v_cmp_le_i32_e32 vcc, s9, v2
	v_mul_lo_u32 v10, v10, v5
	v_add_nc_u32_e32 v5, s8, v12
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v2, v2, v3, vcc
	v_cmp_le_i32_e32 vcc, s9, v12
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_2)
	v_mul_lo_u32 v11, v11, v2
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v12, v12, v5, vcc
	v_cmp_le_i32_e32 vcc, s9, v7
	v_mul_lo_u32 v28, v28, v12
	v_bfe_u32 v12, v13, 16, 8
	v_add3_u32 v11, v11, v9, v10
	v_bfe_u32 v10, v13, 8, 8
	v_add_nc_u32_e32 v9, s8, v7
	v_lshrrev_b32_e32 v13, 24, v13
	s_delay_alu instid0(VALU_DEP_4)
	v_add3_u32 v1, v1, v11, v28
	v_add_nc_u32_e32 v28, s8, v12
	v_add_nc_u32_e32 v11, s8, v10
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v7, v7, v9, vcc
	v_cmp_le_i32_e32 vcc, s9, v10
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_4) | instid1(VALU_DEP_3)
	v_mul_lo_u32 v44, v44, v7
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v10, v10, v11, vcc
	v_cmp_le_i32_e32 vcc, s9, v12
	v_bfe_u32 v2, v14, 8, 8
	v_mul_lo_u32 v45, v45, v10
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v12, v12, v28, vcc
	v_cmp_le_i32_e32 vcc, s9, v13
	v_add_nc_u32_e32 v3, s8, v2
	v_bfe_u32 v5, v30, 8, 4
	v_bfe_u32 v7, v14, 16, 8
	v_mul_lo_u32 v46, v46, v12
	v_add_nc_u32_e32 v5, -8, v5
	v_add_nc_u32_e32 v9, s8, v7
	v_bfe_u32 v10, v30, 16, 4
	s_delay_alu instid0(VALU_DEP_4)
	v_add3_u32 v46, v46, v44, v45
	v_bfe_u32 v45, v14, 0, 8
	v_add_nc_u32_e32 v44, s8, v13
	v_add_nc_u32_e32 v10, -8, v10
	v_lshrrev_b32_e32 v14, 24, v14
	s_wait_alu 0xfffd
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_4)
	v_cndmask_b32_e32 v13, v13, v44, vcc
	v_cmp_le_i32_e32 vcc, s9, v45
	v_bfe_u32 v30, v30, 24, 4
	v_add_nc_u32_e32 v11, s8, v14
	v_mul_lo_u32 v29, v29, v13
	v_add_nc_u32_e32 v30, -8, v30
	v_bfe_u32 v12, v15, 0, 8
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_3) | instid1(VALU_DEP_1)
	v_add_nc_u32_e32 v13, s8, v12
	v_add3_u32 v1, v1, v46, v29
	v_add_nc_u32_e32 v46, s8, v45
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v45, v45, v46, vcc
	v_cmp_le_i32_e32 vcc, s9, v2
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_4) | instid1(VALU_DEP_3)
	v_mul_lo_u32 v47, v47, v45
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v2, v2, v3, vcc
	v_cmp_le_i32_e32 vcc, s9, v7
	v_bfe_u32 v28, v15, 8, 8
	v_mul_lo_u32 v5, v5, v2
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v7, v7, v9, vcc
	v_cmp_le_i32_e32 vcc, s9, v14
	v_add_nc_u32_e32 v29, s8, v28
	v_bfe_u32 v44, v15, 16, 8
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v10, v10, v7
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v14, v14, v11, vcc
	v_cmp_le_i32_e32 vcc, s9, v12
	v_add_nc_u32_e32 v45, s8, v44
	v_bfe_u32 v46, v31, 16, 4
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v30, v30, v14
	v_and_b32_e32 v14, 15, v31
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v12, v12, v13, vcc
	v_cmp_le_i32_e32 vcc, s9, v28
	v_add3_u32 v10, v10, v47, v5
	v_add_nc_u32_e32 v46, -8, v46
	v_lshrrev_b32_e32 v15, 24, v15
	v_add_nc_u32_e32 v14, -8, v14
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v28, v28, v29, vcc
	v_cmp_le_i32_e32 vcc, s9, v44
	v_add3_u32 v1, v1, v10, v30
	v_bfe_u32 v30, v31, 8, 4
	v_bfe_u32 v31, v31, 24, 4
	v_add_nc_u32_e32 v47, s8, v15
	v_mul_lo_u32 v14, v14, v12
	s_wait_loadcnt 0x5
	v_bfe_u32 v2, v32, 8, 4
	v_bfe_u32 v3, v32, 16, 4
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v44, v44, v45, vcc
	v_cmp_le_i32_e32 vcc, s9, v15
	v_add_nc_u32_e32 v30, -8, v30
	v_add_nc_u32_e32 v31, -8, v31
	v_and_b32_e32 v5, 15, v33
	v_bfe_u32 v7, v33, 8, 4
	v_add_nc_u32_e32 v2, -8, v2
	v_add_nc_u32_e32 v3, -8, v3
	v_bfe_u32 v9, v33, 16, 4
	v_mul_lo_u32 v46, v46, v44
	v_bfe_u32 v33, v33, 24, 4
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v15, v15, v47, vcc
	v_and_b32_e32 v47, 15, v32
	v_bfe_u32 v32, v32, 24, 4
	v_mul_lo_u32 v30, v30, v28
	v_and_b32_e32 v10, 15, v34
	v_add_nc_u32_e32 v5, -8, v5
	v_add_nc_u32_e32 v7, -8, v7
	v_bfe_u32 v11, v34, 8, 4
	v_add_nc_u32_e32 v9, -8, v9
	v_bfe_u32 v12, v34, 16, 4
	v_add_nc_u32_e32 v33, -8, v33
	v_mul_lo_u32 v31, v31, v15
	v_add_nc_u32_e32 v47, -8, v47
	s_wait_loadcnt 0x4
	v_bfe_u32 v13, v16, 0, 8
	v_add_nc_u32_e32 v32, -8, v32
	v_bfe_u32 v15, v16, 8, 8
	v_add_nc_u32_e32 v10, -8, v10
	v_add3_u32 v46, v46, v14, v30
	v_add_nc_u32_e32 v11, -8, v11
	v_add_nc_u32_e32 v12, -8, v12
	v_bfe_u32 v29, v16, 16, 8
	v_cmp_le_i32_e32 vcc, s9, v13
	v_add_nc_u32_e32 v14, s8, v13
	v_lshrrev_b32_e32 v16, 24, v16
	v_add_nc_u32_e32 v28, s8, v15
	v_add3_u32 v1, v1, v46, v31
	v_add_nc_u32_e32 v30, s8, v29
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v13, v13, v14, vcc
	v_cmp_le_i32_e32 vcc, s9, v15
	v_add_nc_u32_e32 v31, s8, v16
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_4) | instid1(VALU_DEP_3)
	v_mul_lo_u32 v47, v47, v13
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v15, v15, v28, vcc
	v_cmp_le_i32_e32 vcc, s9, v29
	v_bfe_u32 v45, v17, 8, 8
	v_mul_lo_u32 v2, v2, v15
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v29, v29, v30, vcc
	v_cmp_le_i32_e32 vcc, s9, v16
	v_add_nc_u32_e32 v46, s8, v45
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_1)
	v_mul_lo_u32 v3, v3, v29
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v16, v16, v31, vcc
	v_mul_lo_u32 v32, v32, v16
	v_add3_u32 v3, v3, v47, v2
	v_bfe_u32 v47, v17, 16, 8
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_3) | instid1(VALU_DEP_2)
	v_add_nc_u32_e32 v2, s8, v47
	v_add3_u32 v1, v1, v3, v32
	v_bfe_u32 v32, v17, 0, 8
	v_lshrrev_b32_e32 v17, 24, v17
	v_add_nc_u32_e32 v44, s8, v32
	v_cmp_le_i32_e32 vcc, s9, v32
	v_add_nc_u32_e32 v3, s8, v17
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v32, v32, v44, vcc
	v_cmp_le_i32_e32 vcc, s9, v45
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_2)
	v_mul_lo_u32 v5, v5, v32
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v45, v45, v46, vcc
	v_cmp_le_i32_e32 vcc, s9, v47
	v_mul_lo_u32 v7, v7, v45
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v47, v47, v2, vcc
	v_cmp_le_i32_e32 vcc, s9, v17
	v_bfe_u32 v14, v18, 16, 8
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_2)
	v_mul_lo_u32 v9, v9, v47
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v17, v17, v3, vcc
	v_add_nc_u32_e32 v15, s8, v14
	v_mul_lo_u32 v33, v33, v17
	v_add3_u32 v9, v9, v5, v7
	v_bfe_u32 v5, v18, 0, 8
	s_delay_alu instid0(VALU_DEP_1)
	v_cmp_le_i32_e32 vcc, s9, v5
	v_add_nc_u32_e32 v7, s8, v5
	v_add3_u32 v1, v1, v9, v33
	v_bfe_u32 v9, v18, 8, 8
	v_lshrrev_b32_e32 v18, 24, v18
	v_bfe_u32 v34, v34, 24, 4
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v5, v5, v7, vcc
	v_bfe_u32 v17, v19, 0, 8
	v_add_nc_u32_e32 v13, s8, v9
	v_cmp_le_i32_e32 vcc, s9, v9
	v_add_nc_u32_e32 v16, s8, v18
	v_add_nc_u32_e32 v34, -8, v34
	v_and_b32_e32 v28, 15, v35
	v_mul_lo_u32 v10, v10, v5
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v9, v9, v13, vcc
	v_cmp_le_i32_e32 vcc, s9, v14
	v_bfe_u32 v29, v19, 8, 8
	v_add_nc_u32_e32 v28, -8, v28
	v_bfe_u32 v31, v35, 8, 4
	v_mul_lo_u32 v11, v11, v9
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v14, v14, v15, vcc
	v_cmp_le_i32_e32 vcc, s9, v18
	v_add_nc_u32_e32 v30, s8, v29
	v_add_nc_u32_e32 v31, -8, v31
	v_bfe_u32 v32, v19, 16, 8
	v_mul_lo_u32 v12, v12, v14
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v18, v18, v16, vcc
	v_cmp_le_i32_e32 vcc, s9, v17
	v_add_nc_u32_e32 v33, s8, v32
	v_lshrrev_b32_e32 v19, 24, v19
	s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_3)
	v_mul_lo_u32 v34, v34, v18
	v_add_nc_u32_e32 v18, s8, v17
	v_add3_u32 v12, v12, v10, v11
	v_add_nc_u32_e32 v44, s8, v19
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v17, v17, v18, vcc
	v_cmp_le_i32_e32 vcc, s9, v29
	v_add3_u32 v1, v1, v12, v34
	v_bfe_u32 v34, v35, 16, 4
	v_bfe_u32 v35, v35, 24, 4
	s_wait_loadcnt 0x2
	v_bfe_u32 v45, v20, 0, 8
	v_mul_lo_u32 v28, v28, v17
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v29, v29, v30, vcc
	v_cmp_le_i32_e32 vcc, s9, v32
	v_add_nc_u32_e32 v34, -8, v34
	v_add_nc_u32_e32 v35, -8, v35
	v_and_b32_e32 v47, 15, v36
	v_add_nc_u32_e32 v46, s8, v45
	v_bfe_u32 v2, v20, 8, 8
	v_mul_lo_u32 v31, v31, v29
	v_bfe_u32 v5, v36, 8, 4
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v32, v32, v33, vcc
	v_cmp_le_i32_e32 vcc, s9, v19
	v_add_nc_u32_e32 v47, -8, v47
	v_add_nc_u32_e32 v3, s8, v2
	v_bfe_u32 v7, v20, 16, 8
	v_add_nc_u32_e32 v5, -8, v5
	v_bfe_u32 v10, v36, 16, 4
	v_mul_lo_u32 v34, v34, v32
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v19, v19, v44, vcc
	v_cmp_le_i32_e32 vcc, s9, v45
	v_add_nc_u32_e32 v9, s8, v7
	v_lshrrev_b32_e32 v20, 24, v20
	v_add_nc_u32_e32 v10, -8, v10
	v_bfe_u32 v36, v36, 24, 4
	v_mul_lo_u32 v35, v35, v19
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v45, v45, v46, vcc
	v_cmp_le_i32_e32 vcc, s9, v2
	v_add3_u32 v34, v34, v28, v31
	v_add_nc_u32_e32 v11, s8, v20
	v_add_nc_u32_e32 v36, -8, v36
	v_bfe_u32 v12, v21, 0, 8
	v_mul_lo_u32 v47, v47, v45
	v_and_b32_e32 v14, 15, v37
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v2, v2, v3, vcc
	v_cmp_le_i32_e32 vcc, s9, v7
	v_add3_u32 v1, v1, v34, v35
	v_add_nc_u32_e32 v13, s8, v12
	v_bfe_u32 v15, v21, 8, 8
	v_bfe_u32 v17, v37, 8, 4
	v_add_nc_u32_e32 v14, -8, v14
	v_mul_lo_u32 v5, v5, v2
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v7, v7, v9, vcc
	v_cmp_le_i32_e32 vcc, s9, v20
	v_add_nc_u32_e32 v16, s8, v15
	v_add_nc_u32_e32 v17, -8, v17
	v_bfe_u32 v18, v21, 16, 8
	v_mul_lo_u32 v10, v10, v7
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v20, v20, v11, vcc
	v_cmp_le_i32_e32 vcc, s9, v12
	v_add_nc_u32_e32 v19, s8, v18
	v_lshrrev_b32_e32 v21, 24, v21
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v36, v36, v20
	v_bfe_u32 v20, v37, 16, 4
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v12, v12, v13, vcc
	v_cmp_le_i32_e32 vcc, s9, v15
	v_add3_u32 v10, v10, v47, v5
	v_add_nc_u32_e32 v28, s8, v21
	v_bfe_u32 v37, v37, 24, 4
	v_bfe_u32 v29, v22, 0, 8
	v_add_nc_u32_e32 v20, -8, v20
	v_mul_lo_u32 v14, v14, v12
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v15, v15, v16, vcc
	v_cmp_le_i32_e32 vcc, s9, v18
	v_add3_u32 v1, v1, v10, v36
	v_add_nc_u32_e32 v37, -8, v37
	v_add_nc_u32_e32 v30, s8, v29
	v_and_b32_e32 v31, 15, v38
	v_bfe_u32 v32, v22, 8, 8
	v_mul_lo_u32 v17, v17, v15
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v18, v18, v19, vcc
	v_cmp_le_i32_e32 vcc, s9, v21
	v_bfe_u32 v34, v38, 8, 4
	v_add_nc_u32_e32 v31, -8, v31
	v_add_nc_u32_e32 v33, s8, v32
	v_bfe_u32 v35, v22, 16, 8
	v_mul_lo_u32 v20, v20, v18
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v21, v21, v28, vcc
	v_cmp_le_i32_e32 vcc, s9, v29
	v_add_nc_u32_e32 v34, -8, v34
	v_add_nc_u32_e32 v36, s8, v35
	v_lshrrev_b32_e32 v22, 24, v22
	v_mul_lo_u32 v37, v37, v21
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v29, v29, v30, vcc
	v_cmp_le_i32_e32 vcc, s9, v32
	v_add3_u32 v20, v20, v14, v17
	v_add_nc_u32_e32 v44, s8, v22
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v31, v31, v29
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v32, v32, v33, vcc
	v_cmp_le_i32_e32 vcc, s9, v35
	v_add3_u32 v1, v1, v20, v37
	v_bfe_u32 v37, v38, 16, 4
	v_bfe_u32 v38, v38, 24, 4
	v_bfe_u32 v45, v23, 0, 8
	v_and_b32_e32 v47, 15, v39
	v_mul_lo_u32 v34, v34, v32
	v_bfe_u32 v2, v23, 8, 8
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v35, v35, v36, vcc
	v_cmp_le_i32_e32 vcc, s9, v22
	v_add_nc_u32_e32 v37, -8, v37
	v_add_nc_u32_e32 v38, -8, v38
	v_add_nc_u32_e32 v46, s8, v45
	v_add_nc_u32_e32 v47, -8, v47
	v_bfe_u32 v5, v39, 8, 4
	v_add_nc_u32_e32 v3, s8, v2
	v_bfe_u32 v7, v23, 16, 8
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v22, v22, v44, vcc
	v_cmp_le_i32_e32 vcc, s9, v45
	v_mul_lo_u32 v37, v37, v35
	v_bfe_u32 v10, v39, 16, 4
	v_add_nc_u32_e32 v5, -8, v5
	v_add_nc_u32_e32 v9, s8, v7
	v_mul_lo_u32 v38, v38, v22
	v_lshrrev_b32_e32 v23, 24, v23
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v45, v45, v46, vcc
	v_cmp_le_i32_e32 vcc, s9, v2
	v_add_nc_u32_e32 v10, -8, v10
	v_add3_u32 v37, v37, v31, v34
	v_bfe_u32 v39, v39, 24, 4
	s_wait_loadcnt 0x0
	v_bfe_u32 v12, v24, 0, 8
	v_add_nc_u32_e32 v11, s8, v23
	v_mul_lo_u32 v47, v47, v45
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v2, v2, v3, vcc
	v_cmp_le_i32_e32 vcc, s9, v7
	v_add3_u32 v1, v1, v37, v38
	v_add_nc_u32_e32 v39, -8, v39
	v_add_nc_u32_e32 v13, s8, v12
	v_and_b32_e32 v14, 15, v40
	v_bfe_u32 v15, v24, 8, 8
	v_mul_lo_u32 v5, v5, v2
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v7, v7, v9, vcc
	v_cmp_le_i32_e32 vcc, s9, v23
	v_bfe_u32 v17, v40, 8, 4
	v_add_nc_u32_e32 v14, -8, v14
	v_add_nc_u32_e32 v16, s8, v15
	v_bfe_u32 v18, v24, 16, 8
	v_mul_lo_u32 v10, v10, v7
	v_bfe_u32 v20, v40, 16, 4
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v23, v23, v11, vcc
	v_cmp_le_i32_e32 vcc, s9, v12
	v_add_nc_u32_e32 v17, -8, v17
	v_add_nc_u32_e32 v19, s8, v18
	v_lshrrev_b32_e32 v24, 24, v24
	v_add_nc_u32_e32 v20, -8, v20
	v_bfe_u32 v40, v40, 24, 4
	v_mul_lo_u32 v39, v39, v23
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v12, v12, v13, vcc
	v_cmp_le_i32_e32 vcc, s9, v15
	v_add3_u32 v10, v10, v47, v5
	v_add_nc_u32_e32 v21, s8, v24
	v_add_nc_u32_e32 v40, -8, v40
	v_bfe_u32 v22, v25, 0, 8
	v_mul_lo_u32 v14, v14, v12
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v15, v15, v16, vcc
	v_cmp_le_i32_e32 vcc, s9, v18
	v_add3_u32 v1, v1, v10, v39
	v_add_nc_u32_e32 v23, s8, v22
	v_bfe_u32 v28, v25, 8, 8
	v_mul_lo_u32 v17, v17, v15
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v18, v18, v19, vcc
	v_cmp_le_i32_e32 vcc, s9, v24
	v_bfe_u32 v30, v41, 8, 4
	v_add_nc_u32_e32 v29, s8, v28
	v_bfe_u32 v31, v25, 16, 8
	v_mul_lo_u32 v20, v20, v18
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v24, v24, v21, vcc
	v_cmp_le_i32_e32 vcc, s9, v22
	v_add_nc_u32_e32 v30, -8, v30
	v_add_nc_u32_e32 v32, s8, v31
	v_bfe_u32 v33, v41, 16, 4
	v_lshrrev_b32_e32 v25, 24, v25
	v_mul_lo_u32 v40, v40, v24
	v_and_b32_e32 v24, 15, v41
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v22, v22, v23, vcc
	v_cmp_le_i32_e32 vcc, s9, v28
	v_add3_u32 v20, v20, v14, v17
	v_add_nc_u32_e32 v33, -8, v33
	v_add_nc_u32_e32 v34, s8, v25
	v_bfe_u32 v41, v41, 24, 4
	v_bfe_u32 v35, v26, 0, 8
	v_add_nc_u32_e32 v24, -8, v24
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v28, v28, v29, vcc
	v_cmp_le_i32_e32 vcc, s9, v31
	v_add3_u32 v1, v1, v20, v40
	v_and_b32_e32 v37, 15, v42
	v_add_nc_u32_e32 v41, -8, v41
	v_add_nc_u32_e32 v36, s8, v35
	v_bfe_u32 v38, v26, 8, 8
	v_mul_lo_u32 v24, v24, v22
	v_mul_lo_u32 v30, v30, v28
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v31, v31, v32, vcc
	v_cmp_le_i32_e32 vcc, s9, v25
	v_add_nc_u32_e32 v37, -8, v37
	v_bfe_u32 v40, v42, 8, 4
	v_add_nc_u32_e32 v39, s8, v38
	v_mul_lo_u32 v33, v33, v31
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v25, v25, v34, vcc
	v_cmp_le_i32_e32 vcc, s9, v35
	v_add_nc_u32_e32 v40, -8, v40
	v_bfe_u32 v45, v42, 16, 4
	s_delay_alu instid0(VALU_DEP_4)
	v_mul_lo_u32 v41, v41, v25
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v35, v35, v36, vcc
	v_cmp_le_i32_e32 vcc, s9, v38
	v_add3_u32 v33, v33, v24, v30
	v_add_nc_u32_e32 v45, -8, v45
	v_bfe_u32 v42, v42, 24, 4
	v_mul_lo_u32 v37, v37, v35
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v38, v38, v39, vcc
	v_add3_u32 v1, v1, v33, v41
	v_bfe_u32 v41, v26, 16, 8
	v_lshrrev_b32_e32 v26, 24, v26
	v_add_nc_u32_e32 v42, -8, v42
	v_bfe_u32 v47, v27, 0, 8
	v_and_b32_e32 v3, 15, v43
	v_mul_lo_u32 v40, v40, v38
	v_add_nc_u32_e32 v44, s8, v41
	v_cmp_le_i32_e32 vcc, s9, v41
	v_add_nc_u32_e32 v46, s8, v26
	v_add_nc_u32_e32 v2, s8, v47
	v_bfe_u32 v5, v27, 8, 8
	v_add_nc_u32_e32 v3, -8, v3
	v_bfe_u32 v9, v43, 8, 4
	v_bfe_u32 v10, v27, 16, 8
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v41, v41, v44, vcc
	v_cmp_le_i32_e32 vcc, s9, v26
	v_add_nc_u32_e32 v7, s8, v5
	v_bfe_u32 v12, v43, 16, 4
	v_add_nc_u32_e32 v9, -8, v9
	v_add_nc_u32_e32 v11, s8, v10
	v_mul_lo_u32 v45, v45, v41
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v26, v26, v46, vcc
	v_cmp_le_i32_e32 vcc, s9, v47
	v_add_nc_u32_e32 v12, -8, v12
	v_lshrrev_b32_e32 v27, 24, v27
	v_bfe_u32 v43, v43, 24, 4
	v_mul_lo_u32 v42, v42, v26
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v47, v47, v2, vcc
	v_cmp_le_i32_e32 vcc, s9, v5
	v_add3_u32 v45, v45, v37, v40
	v_add_nc_u32_e32 v13, s8, v27
	v_add_nc_u32_e32 v43, -8, v43
	v_mul_lo_u32 v3, v3, v47
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v5, v5, v7, vcc
	v_cmp_le_i32_e32 vcc, s9, v10
	v_add3_u32 v1, v1, v45, v42
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_2)
	v_mul_lo_u32 v9, v9, v5
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v10, v10, v11, vcc
	v_cmp_le_i32_e32 vcc, s9, v27
	v_mul_lo_u32 v12, v12, v10
	s_wait_alu 0xfffd
	v_cndmask_b32_e32 v27, v27, v13, vcc
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_mul_lo_u32 v43, v43, v27
	v_add3_u32 v12, v12, v3, v9
	v_add3_u32 v1, v1, v12, v43
	s_branch .Lmw_dot_scalar_gfx1201_w64_BB2
.Lmw_dot_scalar_gfx1201_w64_BB6:
	v_mov_b32_e32 v2, 0
	global_load_b32 v2, v2, s[2:3] offset:32
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v2, v2, v0
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_ashrrev_i32_e32 v3, 31, v2
	v_lshlrev_b64_e64 v[2:3], 2, v[2:3]
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_u32 v4, vcc, v8, v2
	s_wait_alu 0xfffd
	v_add_co_ci_u32_e32 v5, vcc, s6, v3, vcc
	global_load_b32 v3, v[4:5], off
	s_wait_loadcnt 0x0
	v_add_nc_u32_e32 v3, v3, v1
	global_store_b32 v[4:5], v3, off
.Lmw_dot_scalar_gfx1201_w64_BB11:
	s_nop 0
	s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
	s_endpgm)MW"

