// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Kaden Schutt <kaden@hipfire.dev>

//! C ABI for `redline-dispatch` — a leaner, safer HipGraph, callable from C/C++.
//!
//! Mirrors the `hipgraph` adapter: create a graph, add kernel nodes with their
//! buffer accesses and dependencies, instantiate, then launch. Handles are
//! opaque `uint32_t` values scoped to their graph. All functions are
//! null-tolerant and return an `int32_t` status (`RL_OK` == 0, negative on
//! error) unless documented otherwise.
//!
//! See `include/redline_dispatch.h` (generated by cbindgen) for the C header.

use std::ffi::{CStr, c_char};

use redline_dispatch::hipgraph::{Graph, GraphExec, Tuning};
use redline_dispatch::mock::MockBackend;
use redline_dispatch::{Access, Dim3, KernelLaunch, NodeId, ReplayToken, ResourceId};

pub const RL_OK: i32 = 0;
pub const RL_ERR_NULL: i32 = -1;
pub const RL_ERR_UTF8: i32 = -2;
pub const RL_ERR_RECORD: i32 = -3;
pub const RL_ERR_COMPILE: i32 = -4;
pub const RL_ERR_REPLAY: i32 = -5;
pub const RL_ERR_HANDLE: i32 = -6;

/// Replay tuning mode. `lanes`/`max_in_flight` are read from the call site.
#[repr(C)]
pub enum RlMode {
    /// One serial lane, terminal-signal completion (safest; == one stream).
    Latency = 0,
    /// `lanes` independent lanes overlap.
    Overlap = 1,
    /// Whole-graph overlap bounded by `max_in_flight`.
    Throughput = 2,
}

/// One buffer access declared by a kernel node.
#[repr(C)]
pub struct RlAccess {
    /// Buffer handle returned by [`rl_graph_buffer`].
    pub buffer: u32,
    pub offset: u64,
    pub len: u64,
    /// `0` = read, non-zero = write.
    pub write: u8,
}

/// Opaque capturing graph. Create with [`rl_graph_new`] / [`rl_graph_new_tuned`].
pub struct RlGraph {
    graph: Graph,
    resources: Vec<ResourceId>,
    nodes: Vec<NodeId>,
}

/// Opaque instantiated graph (the analogue of `hipGraphExec_t`).
pub struct RlGraphExec {
    exec: GraphExec,
}

/// Create an empty graph with default (latency) tuning. Free with
/// [`rl_graph_free`].
#[unsafe(no_mangle)]
pub extern "C" fn rl_graph_new() -> *mut RlGraph {
    Box::into_raw(Box::new(RlGraph {
        graph: Graph::new(),
        resources: Vec::new(),
        nodes: Vec::new(),
    }))
}

/// Create an empty graph with explicit tuning.
#[unsafe(no_mangle)]
pub extern "C" fn rl_graph_new_tuned(lanes: usize, mode: RlMode, max_in_flight: usize) -> *mut RlGraph {
    let tuning = match mode {
        RlMode::Latency => Tuning::latency(),
        RlMode::Overlap => Tuning::overlap(lanes),
        RlMode::Throughput => Tuning::throughput(lanes, max_in_flight),
    };
    Box::into_raw(Box::new(RlGraph {
        graph: Graph::with_tuning(tuning),
        resources: Vec::new(),
        nodes: Vec::new(),
    }))
}

/// Free a graph created by [`rl_graph_new`] / [`rl_graph_new_tuned`].
///
/// # Safety
/// `g` must be a pointer returned by this library, or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graph_free(g: *mut RlGraph) {
    if !g.is_null() {
        drop(unsafe { Box::from_raw(g) });
    }
}

/// Declare a device buffer (label + byte size). Writes an opaque buffer handle
/// to `out_handle`.
///
/// # Safety
/// `g`, `label`, `out_handle` must be valid or null; `label` NUL-terminated.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graph_buffer(
    g: *mut RlGraph,
    label: *const c_char,
    size: u64,
    out_handle: *mut u32,
) -> i32 {
    let Some(g) = (unsafe { g.as_mut() }) else {
        return RL_ERR_NULL;
    };
    if label.is_null() || out_handle.is_null() {
        return RL_ERR_NULL;
    }
    let Ok(label) = (unsafe { CStr::from_ptr(label) }).to_str() else {
        return RL_ERR_UTF8;
    };
    match g.graph.buffer(label, size) {
        Ok(id) => {
            let handle = g.resources.len() as u32;
            g.resources.push(id);
            unsafe { *out_handle = handle };
            RL_OK
        }
        Err(_) => RL_ERR_RECORD,
    }
}

/// Add a kernel node. `deps` are node handles (may be null/empty for a root);
/// `accesses` declares the buffer reads/writes. Writes the new node handle to
/// `out_handle`.
///
/// # Safety
/// Pointers must be valid for their stated lengths or null; `name`
/// NUL-terminated.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graph_kernel(
    g: *mut RlGraph,
    name: *const c_char,
    grid_x: u32,
    grid_y: u32,
    grid_z: u32,
    block_x: u32,
    block_y: u32,
    block_z: u32,
    accesses: *const RlAccess,
    n_access: usize,
    deps: *const u32,
    n_deps: usize,
    out_handle: *mut u32,
) -> i32 {
    let Some(g) = (unsafe { g.as_mut() }) else {
        return RL_ERR_NULL;
    };
    if name.is_null() || out_handle.is_null() {
        return RL_ERR_NULL;
    }
    let Ok(name) = (unsafe { CStr::from_ptr(name) }).to_str() else {
        return RL_ERR_UTF8;
    };
    let (Ok(grid), Ok(block)) = (Dim3::new(grid_x, grid_y, grid_z), Dim3::new(block_x, block_y, block_z))
    else {
        return RL_ERR_RECORD;
    };
    let Ok(launch) = KernelLaunch::new(name, grid, block) else {
        return RL_ERR_RECORD;
    };

    let acc_slice: &[RlAccess] = if accesses.is_null() || n_access == 0 {
        &[]
    } else {
        unsafe { std::slice::from_raw_parts(accesses, n_access) }
    };
    let mut acc_vec = Vec::with_capacity(acc_slice.len());
    for a in acc_slice {
        let Some(&res) = g.resources.get(a.buffer as usize) else {
            return RL_ERR_HANDLE;
        };
        let Ok(region) = g.graph.region(res, a.offset, a.len) else {
            return RL_ERR_RECORD;
        };
        acc_vec.push(if a.write != 0 {
            Access::write(region)
        } else {
            Access::read(region)
        });
    }

    let dep_slice: &[u32] = if deps.is_null() || n_deps == 0 {
        &[]
    } else {
        unsafe { std::slice::from_raw_parts(deps, n_deps) }
    };
    let mut dep_vec = Vec::with_capacity(dep_slice.len());
    for &d in dep_slice {
        let Some(&node) = g.nodes.get(d as usize) else {
            return RL_ERR_HANDLE;
        };
        dep_vec.push(node);
    }

    let result = if dep_vec.is_empty() {
        g.graph.kernel(launch, acc_vec)
    } else {
        g.graph.kernel_after(launch, acc_vec, dep_vec)
    };
    match result {
        Ok(node) => {
            let handle = g.nodes.len() as u32;
            g.nodes.push(node);
            unsafe { *out_handle = handle };
            RL_OK
        }
        Err(_) => RL_ERR_RECORD,
    }
}

/// Instantiate the captured graph into a replayable exec. Writes the exec
/// pointer to `out_exec`. Hazards are validated here; an unsafe graph returns
/// `RL_ERR_COMPILE`.
///
/// # Safety
/// `g`, `out_exec` must be valid or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graph_instantiate(g: *mut RlGraph, out_exec: *mut *mut RlGraphExec) -> i32 {
    let Some(g) = (unsafe { g.as_ref() }) else {
        return RL_ERR_NULL;
    };
    if out_exec.is_null() {
        return RL_ERR_NULL;
    }
    match g.graph.instantiate() {
        Ok(exec) => {
            unsafe { *out_exec = Box::into_raw(Box::new(RlGraphExec { exec })) };
            RL_OK
        }
        Err(_) => RL_ERR_COMPILE,
    }
}

/// Free an exec from [`rl_graph_instantiate`].
///
/// # Safety
/// `e` must be a pointer returned by this library, or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graphexec_free(e: *mut RlGraphExec) {
    if !e.is_null() {
        drop(unsafe { Box::from_raw(e) });
    }
}

/// Number of logical replay lanes the plan compiled to (0 if `e` is null).
///
/// # Safety
/// `e` must be valid or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graphexec_lane_count(e: *const RlGraphExec) -> usize {
    match unsafe { e.as_ref() } {
        Some(e) => e.exec.plan().lane_count().get(),
        None => 0,
    }
}

/// Write the plan's 32-byte fingerprint to `out32`.
///
/// # Safety
/// `e` valid or null; `out32` must point to at least 32 writable bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graphexec_fingerprint(e: *const RlGraphExec, out32: *mut u8) -> i32 {
    let Some(e) = (unsafe { e.as_ref() }) else {
        return RL_ERR_NULL;
    };
    if out32.is_null() {
        return RL_ERR_NULL;
    }
    let fp = e.exec.plan().fingerprint().as_bytes();
    unsafe { std::ptr::copy_nonoverlapping(fp.as_ptr(), out32, 32) };
    RL_OK
}

/// Validate the plan by replaying it once against the in-process mock backend
/// (no GPU). Confirms ordering and fences are consistent; returns `RL_OK` or
/// `RL_ERR_REPLAY`. Real HIP / public-AQL replay is bound at integration time.
///
/// # Safety
/// `e` must be valid or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graphexec_launch_mock(e: *const RlGraphExec) -> i32 {
    let Some(e) = (unsafe { e.as_ref() }) else {
        return RL_ERR_NULL;
    };
    let mut backend = MockBackend::default();
    match e.exec.launch(&mut backend, ReplayToken(0)) {
        Ok(_) => RL_OK,
        Err(_) => RL_ERR_REPLAY,
    }
}

/// ABI version of this library.
#[unsafe(no_mangle)]
pub extern "C" fn rl_abi_version() -> u32 {
    1
}
