// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Kaden Schutt <kaden@hipfire.dev>

//! C ABI for `redline-dispatch` — a leaner, safer HipGraph, callable from C/C++.
//!
//! Mirrors the `hipgraph` adapter: create a graph, add kernel nodes with their
//! buffer accesses and dependencies, instantiate, then launch. Handles are
//! opaque `uint32_t` values scoped to their graph. All functions are
//! null-tolerant and return an `int32_t` status (`RL_OK` == 0, negative on
//! error) unless documented otherwise.
//!
//! See `include/redline_dispatch.h` (generated by cbindgen) for the C header.

use std::collections::BTreeMap;
use std::ffi::{CStr, c_char};

use redline_dispatch::aql::{Executable, NodeDispatch, lower_plan_to_pm4_ib};
use redline_dispatch::hipgraph::{Graph, GraphExec, Tuning};
use redline_dispatch::mock::MockBackend;
use redline_dispatch::{Access, Dim3, KernelLaunch, NodeId, ReplayToken, ResourceId};

pub const RL_OK: i32 = 0;
pub const RL_ERR_NULL: i32 = -1;
pub const RL_ERR_UTF8: i32 = -2;
pub const RL_ERR_RECORD: i32 = -3;
pub const RL_ERR_COMPILE: i32 = -4;
pub const RL_ERR_REPLAY: i32 = -5;
pub const RL_ERR_HANDLE: i32 = -6;
pub const RL_ERR_CERTIFICATION: i32 = -7;

/// Real-GPU retained-PM4 replay (engine supplies its own kernels + kernargs).
pub mod gpu;
mod validate;

use gpu::{RlGpu, RlModule};

/// Replay tuning mode. `lanes`/`max_in_flight` are read from the call site.
#[repr(C)]
pub enum RlMode {
    /// One serial lane, terminal-signal completion (safest; == one stream).
    Latency = 0,
    /// `lanes` independent lanes overlap.
    Overlap = 1,
    /// Whole-graph overlap bounded by `max_in_flight`.
    Throughput = 2,
}

/// One buffer access declared by a kernel node.
#[repr(C)]
pub struct RlAccess {
    /// Buffer handle returned by [`rl_graph_buffer`].
    pub buffer: u32,
    pub offset: u64,
    pub len: u64,
    /// `0` = read, non-zero = write.
    pub write: u8,
}

#[derive(Clone)]
struct NodeMeta {
    executable: Executable,
    symbol: String,
    kernargs: Vec<u8>,
    grid: [u32; 3],
    block: [u16; 3],
    dyn_group: u32,
}

/// Opaque capturing graph. Create with [`rl_graph_new`] / [`rl_graph_new_tuned`].
pub struct RlGraph {
    graph: Graph,
    resources: Vec<ResourceId>,
    nodes: Vec<NodeId>,
    node_meta: Vec<Option<NodeMeta>>,
}

/// Opaque instantiated graph (the analogue of `hipGraphExec_t`).
pub struct RlGraphExec {
    exec: GraphExec,
    nodes: Vec<NodeId>,
    node_meta: BTreeMap<NodeId, NodeMeta>,
}

/// Create an empty graph with default (latency) tuning. Free with
/// [`rl_graph_free`].
#[unsafe(no_mangle)]
pub extern "C" fn rl_graph_new() -> *mut RlGraph {
    Box::into_raw(Box::new(RlGraph {
        graph: Graph::new(),
        resources: Vec::new(),
        nodes: Vec::new(),
        node_meta: Vec::new(),
    }))
}

/// Create an empty graph with explicit tuning.
#[unsafe(no_mangle)]
pub extern "C" fn rl_graph_new_tuned(
    lanes: usize,
    mode: RlMode,
    max_in_flight: usize,
) -> *mut RlGraph {
    let tuning = match mode {
        RlMode::Latency => Tuning::latency(),
        RlMode::Overlap => Tuning::overlap(lanes),
        RlMode::Throughput => Tuning::throughput(lanes, max_in_flight),
    };
    Box::into_raw(Box::new(RlGraph {
        graph: Graph::with_tuning(tuning),
        resources: Vec::new(),
        nodes: Vec::new(),
        node_meta: Vec::new(),
    }))
}

/// Free a graph created by [`rl_graph_new`] / [`rl_graph_new_tuned`].
///
/// # Safety
/// `g` must be a pointer returned by this library, or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graph_free(g: *mut RlGraph) {
    if !g.is_null() {
        drop(unsafe { Box::from_raw(g) });
    }
}

/// Declare a device buffer (label + byte size). Writes an opaque buffer handle
/// to `out_handle`.
///
/// # Safety
/// `g`, `label`, `out_handle` must be valid or null; `label` NUL-terminated.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graph_buffer(
    g: *mut RlGraph,
    label: *const c_char,
    size: u64,
    out_handle: *mut u32,
) -> i32 {
    let Some(g) = (unsafe { g.as_mut() }) else {
        return RL_ERR_NULL;
    };
    if label.is_null() || out_handle.is_null() {
        return RL_ERR_NULL;
    }
    let Ok(label) = (unsafe { CStr::from_ptr(label) }).to_str() else {
        return RL_ERR_UTF8;
    };
    match g.graph.buffer(label, size) {
        Ok(id) => {
            let handle = g.resources.len() as u32;
            g.resources.push(id);
            unsafe { *out_handle = handle };
            RL_OK
        }
        Err(_) => RL_ERR_RECORD,
    }
}

/// Add a kernel node. `deps` are node handles (may be null/empty for a root);
/// `accesses` declares the buffer reads/writes. Writes the new node handle to
/// `out_handle`.
///
/// # Safety
/// Pointers must be valid for their stated lengths or null; `name`
/// NUL-terminated.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graph_kernel(
    g: *mut RlGraph,
    name: *const c_char,
    grid_x: u32,
    grid_y: u32,
    grid_z: u32,
    block_x: u32,
    block_y: u32,
    block_z: u32,
    accesses: *const RlAccess,
    n_access: usize,
    deps: *const u32,
    n_deps: usize,
    out_handle: *mut u32,
) -> i32 {
    let Some(g) = (unsafe { g.as_mut() }) else {
        return RL_ERR_NULL;
    };
    if name.is_null() || out_handle.is_null() {
        return RL_ERR_NULL;
    }
    let Ok(name) = (unsafe { CStr::from_ptr(name) }).to_str() else {
        return RL_ERR_UTF8;
    };
    let (Ok(grid), Ok(block)) = (
        Dim3::new(grid_x, grid_y, grid_z),
        Dim3::new(block_x, block_y, block_z),
    ) else {
        return RL_ERR_RECORD;
    };
    let Ok(launch) = KernelLaunch::new(name, grid, block) else {
        return RL_ERR_RECORD;
    };

    let acc_slice: &[RlAccess] = if accesses.is_null() || n_access == 0 {
        &[]
    } else {
        unsafe { std::slice::from_raw_parts(accesses, n_access) }
    };
    let mut acc_vec = Vec::with_capacity(acc_slice.len());
    for a in acc_slice {
        let Some(&res) = g.resources.get(a.buffer as usize) else {
            return RL_ERR_HANDLE;
        };
        let Ok(region) = g.graph.region(res, a.offset, a.len) else {
            return RL_ERR_RECORD;
        };
        acc_vec.push(if a.write != 0 {
            Access::write(region)
        } else {
            Access::read(region)
        });
    }

    let dep_slice: &[u32] = if deps.is_null() || n_deps == 0 {
        &[]
    } else {
        unsafe { std::slice::from_raw_parts(deps, n_deps) }
    };
    let mut dep_vec = Vec::with_capacity(dep_slice.len());
    for &d in dep_slice {
        let Some(&node) = g.nodes.get(d as usize) else {
            return RL_ERR_HANDLE;
        };
        dep_vec.push(node);
    }

    let result = if dep_vec.is_empty() {
        g.graph.kernel(launch, acc_vec)
    } else {
        g.graph.kernel_after(launch, acc_vec, dep_vec)
    };
    match result {
        Ok(node) => {
            let handle = g.nodes.len() as u32;
            g.nodes.push(node);
            g.node_meta.push(None);
            unsafe { *out_handle = handle };
            RL_OK
        }
        Err(_) => RL_ERR_RECORD,
    }
}

/// Add a kernel node with the executable and packed kernarg bytes required by
/// real PM4 replay. Grid dimensions are global work-item counts.
///
/// # Safety
///
/// Pointers must be valid for their stated lengths or null. `symbol` must be
/// NUL-terminated. A null `kernarg` is accepted only when `kernarg_len == 0`.
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub unsafe extern "C" fn rl_graph_kernel_ex(
    g: *mut RlGraph,
    module: *const RlModule,
    symbol: *const c_char,
    grid_x: u32,
    grid_y: u32,
    grid_z: u32,
    block_x: u32,
    block_y: u32,
    block_z: u32,
    dyn_group_bytes: u32,
    kernarg: *const u8,
    kernarg_len: usize,
    accesses: *const RlAccess,
    n_access: usize,
    deps: *const u32,
    n_deps: usize,
    out_handle: *mut u32,
) -> i32 {
    let Some(module) = (unsafe { module.as_ref() }) else {
        return RL_ERR_NULL;
    };
    if g.is_null() || symbol.is_null() || out_handle.is_null() {
        return RL_ERR_NULL;
    }
    if kernarg.is_null() && kernarg_len != 0 {
        return RL_ERR_NULL;
    }
    let Ok(symbol_text) = (unsafe { CStr::from_ptr(symbol) }).to_str() else {
        return RL_ERR_UTF8;
    };
    let Ok(block) = u16::try_from(block_x)
        .and_then(|x| Ok([x, u16::try_from(block_y)?, u16::try_from(block_z)?]))
    else {
        return RL_ERR_RECORD;
    };
    let kernargs = if kernarg_len == 0 {
        Vec::new()
    } else {
        unsafe { std::slice::from_raw_parts(kernarg, kernarg_len) }.to_vec()
    };
    let meta = NodeMeta {
        executable: module.executable.clone(),
        symbol: symbol_text.to_owned(),
        kernargs,
        grid: [grid_x, grid_y, grid_z],
        block,
        dyn_group: dyn_group_bytes,
    };
    let status = unsafe {
        rl_graph_kernel(
            g, symbol, grid_x, grid_y, grid_z, block_x, block_y, block_z, accesses, n_access, deps,
            n_deps, out_handle,
        )
    };
    if status != RL_OK {
        return status;
    }
    let handle = unsafe { *out_handle } as usize;
    // SAFETY: rl_graph_kernel succeeded, so `g` is non-null and appended the
    // side-table entry addressed by the returned handle.
    unsafe { &mut *g }.node_meta[handle] = Some(meta);
    RL_OK
}

/// Add an edge from `from_handle` to `to_handle`; the destination will not run
/// until the source has completed.
///
/// # Safety
///
/// `g` must be a live graph pointer or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graph_add_dependency(
    g: *mut RlGraph,
    from_handle: u32,
    to_handle: u32,
) -> i32 {
    let Some(g) = (unsafe { g.as_mut() }) else {
        return RL_ERR_NULL;
    };
    let Some(&from) = g.nodes.get(from_handle as usize) else {
        return RL_ERR_HANDLE;
    };
    let Some(&to) = g.nodes.get(to_handle as usize) else {
        return RL_ERR_HANDLE;
    };
    match g.graph.recorder().depends_on(to, from) {
        Ok(_) => RL_OK,
        Err(_) => RL_ERR_RECORD,
    }
}

/// Instantiate the captured graph into a replayable exec. Writes the exec
/// pointer to `out_exec`. Hazards are validated here; an unsafe graph returns
/// `RL_ERR_COMPILE`.
///
/// # Safety
/// `g`, `out_exec` must be valid or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graph_instantiate(
    g: *mut RlGraph,
    out_exec: *mut *mut RlGraphExec,
) -> i32 {
    let Some(g) = (unsafe { g.as_ref() }) else {
        return RL_ERR_NULL;
    };
    if out_exec.is_null() {
        return RL_ERR_NULL;
    }
    match g.graph.instantiate() {
        Ok(exec) => {
            let node_meta = g
                .nodes
                .iter()
                .copied()
                .zip(&g.node_meta)
                .filter_map(|(node, meta)| meta.clone().map(|meta| (node, meta)))
                .collect();
            let exec = RlGraphExec {
                exec,
                nodes: g.nodes.clone(),
                node_meta,
            };
            unsafe { *out_exec = Box::into_raw(Box::new(exec)) };
            RL_OK
        }
        Err(_) => RL_ERR_COMPILE,
    }
}

/// Free an exec from [`rl_graph_instantiate`].
///
/// # Safety
/// `e` must be a pointer returned by this library, or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graphexec_free(e: *mut RlGraphExec) {
    if !e.is_null() {
        drop(unsafe { Box::from_raw(e) });
    }
}

/// Number of logical replay lanes the plan compiled to (0 if `e` is null).
///
/// # Safety
/// `e` must be valid or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graphexec_lane_count(e: *const RlGraphExec) -> usize {
    match unsafe { e.as_ref() } {
        Some(e) => e.exec.plan().lane_count().get(),
        None => 0,
    }
}

/// Write the plan's 32-byte fingerprint to `out32`.
///
/// # Safety
/// `e` valid or null; `out32` must point to at least 32 writable bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graphexec_fingerprint(e: *const RlGraphExec, out32: *mut u8) -> i32 {
    let Some(e) = (unsafe { e.as_ref() }) else {
        return RL_ERR_NULL;
    };
    if out32.is_null() {
        return RL_ERR_NULL;
    }
    let fp = e.exec.plan().fingerprint().as_bytes();
    unsafe { std::ptr::copy_nonoverlapping(fp.as_ptr(), out32, 32) };
    RL_OK
}

/// Lower this instantiated graph to one per-generation PM4 IB, submit it once,
/// and wait for completion.
///
/// # Safety
///
/// `gpu` and `e` must be live pointers or null. Device pointers embedded in
/// node kernargs must stay GPU-accessible through the call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graphexec_launch(gpu: *const RlGpu, e: *const RlGraphExec) -> i32 {
    let Some(gpu) = (unsafe { gpu.as_ref() }) else {
        return RL_ERR_NULL;
    };
    let Some(e) = (unsafe { e.as_ref() }) else {
        return RL_ERR_NULL;
    };
    let mut kernels = BTreeMap::new();
    for (&node, meta) in &e.node_meta {
        let Ok(kernel) = meta.executable.kernel(&meta.symbol) else {
            return RL_ERR_RECORD;
        };
        kernels.insert(node, kernel);
    }
    let replay = lower_plan_to_pm4_ib(&gpu.device, &gpu.pool, e.exec.plan(), |node| {
        let meta = e.node_meta.get(&node)?;
        Some(NodeDispatch {
            kernel: kernels.get(&node)?,
            kernargs: &meta.kernargs,
            grid: meta.grid,
            block: meta.block,
            dyn_group: meta.dyn_group,
        })
    });
    let mut replay = match replay {
        Ok(replay) => replay,
        Err(error) => {
            eprintln!("redline: PM4 graph launch IB creation failed: {error}");
            return RL_ERR_COMPILE;
        }
    };
    // SAFETY: replay retains kernarg allocations and code objects; the C caller
    // upholds the lifetime of pointees embedded in the packed bytes.
    match unsafe { replay.replay_and_wait() } {
        Ok(()) => RL_OK,
        Err(_) => RL_ERR_REPLAY,
    }
}

/// Replace the packed kernarg bytes bound to one instantiated node.
///
/// # Safety
///
/// `e` must be live and mutable. `kernarg` must be valid for `len` bytes; null
/// is accepted only when `len == 0`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graphexec_set_node_kernargs(
    e: *mut RlGraphExec,
    node_handle: u32,
    kernarg: *const u8,
    len: usize,
) -> i32 {
    let Some(e) = (unsafe { e.as_mut() }) else {
        return RL_ERR_NULL;
    };
    if kernarg.is_null() && len != 0 {
        return RL_ERR_NULL;
    }
    let Some(&node) = e.nodes.get(node_handle as usize) else {
        return RL_ERR_HANDLE;
    };
    let Some(meta) = e.node_meta.get_mut(&node) else {
        return RL_ERR_HANDLE;
    };
    let bytes = if len == 0 {
        &[]
    } else {
        unsafe { std::slice::from_raw_parts(kernarg, len) }
    };
    meta.kernargs.clear();
    meta.kernargs.extend_from_slice(bytes);
    RL_OK
}

/// Validate the plan by replaying it once against the in-process mock backend
/// (no GPU). Confirms ordering and fences are consistent; returns `RL_OK` or
/// `RL_ERR_REPLAY`. Real HIP / public-AQL replay is bound at integration time.
///
/// # Safety
/// `e` must be valid or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rl_graphexec_launch_mock(e: *const RlGraphExec) -> i32 {
    let Some(e) = (unsafe { e.as_ref() }) else {
        return RL_ERR_NULL;
    };
    let mut backend = MockBackend::default();
    match e.exec.launch(&mut backend, ReplayToken(0)) {
        Ok(_) => RL_OK,
        Err(_) => RL_ERR_REPLAY,
    }
}

/// ABI version of this library.
#[unsafe(no_mangle)]
pub extern "C" fn rl_abi_version() -> u32 {
    1
}

#[cfg(test)]
mod tests {
    use std::ffi::CString;

    use super::*;

    #[test]
    fn dependency_api_orders_existing_nodes() {
        let graph = rl_graph_new();
        let name = CString::new("kernel").unwrap();
        let mut first = u32::MAX;
        let mut second = u32::MAX;
        // SAFETY: all pointers are live for the duration of each call.
        assert_eq!(
            unsafe {
                rl_graph_kernel(
                    graph,
                    name.as_ptr(),
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    std::ptr::null(),
                    0,
                    std::ptr::null(),
                    0,
                    &mut first,
                )
            },
            RL_OK
        );
        assert_eq!(
            unsafe {
                rl_graph_kernel(
                    graph,
                    name.as_ptr(),
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    std::ptr::null(),
                    0,
                    std::ptr::null(),
                    0,
                    &mut second,
                )
            },
            RL_OK
        );
        assert_eq!(
            unsafe { rl_graph_add_dependency(graph, first, second) },
            RL_OK
        );

        let mut exec = std::ptr::null_mut();
        assert_eq!(unsafe { rl_graph_instantiate(graph, &mut exec) }, RL_OK);
        // SAFETY: successful instantiation returned a live exec pointer.
        let dispatches = unsafe { &*exec }.exec.plan().dispatches();
        assert_eq!(dispatches[1].dependencies(), &[dispatches[0].node()]);

        unsafe {
            rl_graphexec_free(exec);
            rl_graph_free(graph);
        }
    }
}
